'use strict';
const worldNames=['Ptačí háj','Tržní přístav','Údolí dílen','Město mostů','Jezerní laboratoř','Horská železnice','Energetické město','Inženýrská stanice','Rada budoucnosti'];
const subtitles=['Malé příběhy mezi větvemi','Svačina pro všechny','Co roste na zahradě','Zahrada u nového mostu','Kolik místa potřebuje voda','Z mapy do skutečných hor','Co znamená úspora','Cesta k hvězdárně','Rozhodnutí, která dávají smysl'];
const stories=[
['Na větvi sedí 6 sýkorek.','2 sýkorky odletí do lesa.'],
['Chystáme svačinu pro 4 děti.','Každé dítě dostane 3 rohlíky.'],
['Na zahradě máme 6 záhonů.','Na každém záhonu rostou 4 sazenice rajčat.'],
['U domu je obdélníková zahrada. Je dlouhá 8 metrů a široká 5 metrů.','Kolem zahrady chceme postavit plot. Na jedné straně bude branka široká 2 metry. V místě branky plot nebude.'],
['Chceme nalít vodu do prázdného akvária. Jeho vnitřní délka je 100 cm, šířka 40 cm a výška 50 cm.','Do akvária nalijeme 65 litrů vody. Není v něm písek ani žádné dekorace.'],
['Plánujeme výlet vlakem. Na mapě měří vybraná trať 8 cm.','Mapa má měřítko 1 : 25 000. To znamená, že 1 cm na mapě představuje 25 000 cm ve skutečnosti.'],
['Veřejné osvětlení dříve spotřebovalo každý den 800 kWh elektrické energie.','Po výměně lamp spotřebuje za den 680 kWh. Chceme porovnat úsporu s původní spotřebou.'],
['U hvězdárny je plošina ve výšce 4 metry nad vodorovnou zemí. Stěna pod plošinou je svislá.','K plošině přistavíme žebřík. Jeho dolní konec bude na zemi 3 metry od stěny.'],
['Vybíráme mezi dvěma nabídkami telefonního operátora. U nabídky A zaplatíme každý měsíc 100 Kč a k tomu 4 Kč za každou provolanou minutu.','U nabídky B zaplatíme každý měsíc 200 Kč a k tomu 2 Kč za každou provolanou minutu. Žádné další poplatky nepočítáme.']
];
const questions=['Kolik sýkorek zůstane na větvi?','Kolik rohlíků potřebujeme pro všechny 4 děti?','Kolik sazenic rajčat roste na celé zahradě?','Kolik metrů plotu potřebujeme?','Jak vysoko bude sahat voda ode dna akvária?','Jak dlouhá je trať ve skutečnosti? Odpověz v kilometrech.','O kolik procent původní spotřeby se spotřeba snížila?','Jak dlouhý musí být žebřík, aby dosáhl přesně k plošině?','Při kolika provolaných minutách zaplatíme za obě nabídky stejnou částku?'];
tasks.forEach((t,i)=>{t.story=stories[i];t.question=questions[i]});
tasks[1].model='4 děti. Každému dítěti patří 3 rohlíky.';
tasks[2].model='6 záhonů. Na každém záhonu rostou 4 sazenice rajčat.';
tasks[8].paths=['Zapíšu obě celkové ceny a najdu, kdy se rovnají.','Zjistím, za kolik minut se vyrovná rozdíl měsíčních poplatků.','Porovnám jen měsíční poplatky. Nabídka A bude vždy levnější.'];
tasks[8].explain=['Označím počet minut písmenem x. Celkové ceny jsou 100 + 4x a 200 + 2x. Hledám takové x, při kterém jsou stejné.','U B zaplatím každý měsíc o 100 Kč více. Za každou minutu ale ušetřím 2 Kč. Hledám, za kolik minut ušetřím právě těch 100 Kč.','Při 100 minutách zaplatím za A 500 Kč a za B 400 Kč. Samotný měsíční poplatek tedy nestačí k rozhodnutí.'];
const birdMissions=[[6,2],[5,1],[7,3],[8,2],[6,3],[9,4],[7,2],[8,5],[10,4],[9,3]];
const KEY='fajn-rozumim-v2';let progress={};try{const raw=localStorage.getItem(KEY);const p=JSON.parse(raw||'{}');if(p&&typeof p==='object'&&!Array.isArray(p))progress=p;if(!raw){const old=JSON.parse(localStorage.getItem('fajn-rozumim-v1')||'{}');if(Array.isArray(old.completed))old.completed.forEach(i=>{if(Number.isInteger(i)&&i>=0&&i<9)progress[i]=[0]})}}catch{}
let w=0,mission=0,stage=0,sound=true,moved=new Set(),groups=[],route=null,bonus=false,hint=0,feedbackText='',feedbackBad=false,modelValue='',selected=null,answerDraft='',celebrate=false;
const app=document.getElementById('app');const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function done(i){return Array.isArray(progress[i])?progress[i].filter(n=>Number.isInteger(n)&&n>=0&&n<(i===0?10:1)):[]}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(progress))}catch{feedbackText='Pokrok se nepodařilo uložit. Prohlížeč nepovoluje ukládání.'}}
function birdCount(n){return `${n} ${n===1?'sýkorka':n<5?'sýkorky':'sýkorek'}`}
function birdAcc(n){return `${n} ${n===1?'sýkorku':n<5?'sýkorky':'sýkorek'}`}
function t(){if(w)return tasks[w];const [n,k]=birdMissions[mission];return {...tasks[0],story:[`Na větvi sedí ${birdCount(n)}.`,`Do lesa odletí ${birdCount(k)}.`],answer:n-k,base:n,away:k}}
function tone(ok){if(!sound)return;try{const c=new AudioContext();(ok?[523,659,784]:[220,196]).forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain(),at=c.currentTime+i*.1;o.frequency.value=f;g.gain.setValueAtTime(.055,at);g.gain.exponentialRampToValueAtTime(.001,at+.2);o.connect(g).connect(c.destination);o.start(at);o.stop(at+.22)});setTimeout(()=>c.close(),700)}catch{}}
function say(s){if(!('speechSynthesis'in window)){message('Tento prohlížeč neumí zadání přečíst nahlas.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(s);u.lang='cs-CZ';u.rate=w<3?.82:.95;speechSynthesis.speak(u)}
function stopVoice(){if('speechSynthesis'in window)speechSynthesis.cancel()}
function message(s,bad=false){feedbackText=s;feedbackBad=bad;const el=document.getElementById('feedback');if(el){el.textContent=s;el.classList.toggle('bad',bad)}tone(!bad)}
function art(i,cls=''){return `<div class="world-art ${cls}" style="--x:${i%3*50}%;--y:${Math.floor(i/3)*50}%" aria-hidden="true"></div>`}
function map(){stopVoice();app.innerHTML=`<section class="map-intro"><span class="eyebrow">TVOJE VÝPRAVA</span><h1>Devět světů čeká na svůj příběh.</h1><p>Začni v kterémkoli ročníku. Barvy do světa vracejí až dokončené úkoly.</p></section><section class="world-grid" aria-label="Vyber ročník">${worldNames.map((name,i)=>{const count=done(i).length,reveal=Math.floor(count/10)*10;return `<button class="world-card" data-world="${i}"><div class="world-picture">${art(i,'gray')}${art(i,'color')}<div class="reveal-mask" style="--revealed:${reveal}%"></div><span class="grade">${i+1}<small>ROČNÍK</small></span><span class="enter-label">Vstoupit ↗</span></div><div class="world-copy"><h2>${name}</h2><p>${subtitles[i]}</p><div class="progress-track"><i style="width:${count}%"></i></div><small>${count} / 100 úkolů · ${count?'Výprava začala':'Vstup je volný'}</small></div></button>`}).join('')}</section><footer>Rozpracovaná výprava: Ptačí háj má nyní 10 úkolů, ostatní světy po jedné úvodní misi. Další části doplníme. Pokrok zůstává v tomto prohlížeči.</footer>`;app.querySelectorAll('[data-world]').forEach(b=>{const i=+b.dataset.world;b.querySelector('.color').style.clipPath=`inset(0 ${100-Math.floor(done(i).length/10)*10}% 0 0)`;b.onclick=()=>enter(i)})}
function enter(i,m){stopVoice();w=i;mission=m??(i===0?Math.min(9,birdMissions.findIndex((_,n)=>!done(0).includes(n))<0?0:birdMissions.findIndex((_,n)=>!done(0).includes(n))):0);stage=0;moved=new Set();groups=Array(i===1?4:6).fill(0);route=null;bonus=false;hint=0;modelValue='';selected=null;answerDraft='';feedbackText='';celebrate=false;render()}
function advance(){stage++;hint=0;feedbackText='';selected=null;render()}
function back(){stage=w===0?1:2;route=null;feedbackText='Můžeš zkusit jinou cestu. Tvoje představa zůstává zachovaná.';render()}
function action(label,fn,primary=false){const b=document.createElement('button');b.className='action'+(primary?' primary':'');b.textContent=label;b.onclick=fn;document.getElementById('actions').append(b);return b}
function choices(items,fn){const box=document.createElement('div');box.className='choices';items.forEach((s,i)=>{const b=document.createElement('button');b.className='choice';b.innerHTML=`<span class="choice-index">${String.fromCharCode(65+i)}</span><span>${esc(s)}</span>`;b.onclick=()=>fn(i);box.append(b)});document.getElementById('work').append(box)}
function render(){const task=t(),count=done(w).length,finished=done(w).includes(mission),chapter=Math.floor(count/10);app.innerHTML=`<nav class="crumb"><button id="map-back">← Mapa světů</button><span>${w+1}. ročník <b>/</b> ${worldNames[w]}</span><span>Úkol ${mission+1}${w===0?' z 10':''}</span></nav><section class="play-layout"><div class="story-side"><div class="scene ${celebrate?'celebrate':''}">${art(w,'gray')}${art(w,'color')}<div class="scene-shade"></div><div class="scene-title"><span class="eyebrow">${w===0?'PŘÍBĚHY Z VĚTVE':'MALÁ VÝPRAVA'}</span><h1>${worldNames[w]}</h1></div><div class="scene-status">${chapter?`${chapter}. část světa ožila`:'Svět čeká na první dokončenou desítku'}</div></div><article class="story-paper"><div class="story-heading"><span class="eyebrow">POSLECHNI SI PŘÍBĚH</span><button id="read" class="read-button" aria-label="Přečíst příběh">♫ Přečíst</button></div>${task.story.map(s=>`<p>${esc(s)}</p>`).join('')}<p class="question">${esc(task.question)}</p></article><section class="construction"><div><span class="eyebrow">TVÁ STAVBA</span><h3>${w===0?'Krmítko pro sýkorky':'První krmítko v novém světě'}</h3><p>${count} / 10 stavebních kroků</p></div><div class="feeder"><div class="sprite unfinished"></div><div class="sprite finished" style="clip-path:inset(${100-Math.min(100,count*10)}% 0 0 0)"></div></div>${celebrate?'<div class="flying-planks"><i class="sprite plank"></i><i class="sprite plank"></i><i class="sprite plank"></i></div>':''}</section></div><article class="activity"><div class="step-dots">${['Příběh','Představa','Postup','Ověření'].map((s,i)=>`<span class="${i<=Math.min(3,stage)?'active':''}">${i+1}<small>${s}</small></span>`).join('')}</div><div class="activity-heading"><h2 id="title"></h2><button id="hint" class="hint-button">? Pomoc</button></div><div id="help"></div><div id="work"></div><div id="feedback" class="feedback ${feedbackBad?'bad':''}" role="status">${esc(feedbackText)}</div><div id="actions" class="actions"></div></article></section>`;
app.querySelector('.scene .color').style.clipPath=`inset(0 ${100-chapter*10}% 0 0)`;
document.getElementById('map-back').onclick=map;document.getElementById('read').onclick=()=>say(task.story.join(' ')+' '+task.question);document.getElementById('hint').onclick=showHint;
const title=s=>document.getElementById('title').textContent=s,work=document.getElementById('work');
if(stage===0){title(w===0?'Podívej se na sýkorky.':'Co potřebujeme zjistit?');if(w===0){work.innerHTML=`<p class="instruction">Tady sedí všechny sýkorky. V dalším kroku necháš dvě odletět.</p><div class="bird-preview">${Array.from({length:task.base},()=>'<span class="sprite bird"></span>').join('')}</div>`;work.querySelector('p').textContent=`Tady sedí všechny sýkorky. V dalším kroku necháš odletět ${birdAcc(task.away)}.`;action('Ukázat, co se stalo',advance,true)}else{const correctFirst=w%2===0;choices(correctFirst?[task.question,task.other]:[task.other,task.question],i=>{if(i===(correctFirst?0:1)){advance();tone(true)}else message('Tato otázka se ptá na něco jiného. Přečti si znovu poslední větu příběhu.',true)})}}
if(stage===1){title(w===0?'Nech sýkorky odletět.':w<3?'Sestav si celý příběh.':'Co znamenají údaje?');if(w===0)birdBoard();else if(w<3)groupBoard();else{const models=[null,null,null,{q:'Plot povede…',a:['po okraji zahrady, s volným místem pro branku.','po celé ploše zahrady jako trávník.'],ok:0},{q:'Voda v akváriu…',a:['vyplní celé dno a vytvoří nad ním vrstvu.','bude tvořit jen úzký sloupec u jedné stěny.'],ok:0},{q:'Číslo 8 cm označuje…',a:['délku skutečné železniční tratě.','délku čáry, která představuje trať na mapě.'],ok:1},{q:'Sto procent v této úloze představuje…',a:['novou spotřebu 680 kWh.','původní spotřebu 800 kWh.'],ok:1},{q:'Žebřík v tomto příběhu…',a:['spojuje dolní konec na zemi přímo s plošinou.','vede nejprve po zemi a potom svisle podél zdi.'],ok:0},{q:'Celková měsíční cena se skládá…',a:['jen z ceny za jednu minutu.','z měsíčního poplatku a ceny všech provolaných minut.'],ok:1}][w];work.innerHTML=`<p class="instruction">${models.q}</p>`;choices(models.a,i=>{if(i===models.ok){advance();tone(true)}else message('Zkus si situaci představit vlastními slovy. '+(w===8?'Poplatek platíš i tehdy, když nevoláš. Za hovory pak platíš navíc.':'Která možnost popisuje právě náš příběh?'),true)})}}
if(stage===2){title(w===0?'Jak zapíšeme odlet?':'Na rozcestí si vyber cestu.');if(w===0){work.innerHTML=`<p class="instruction">Na začátku na větvi sedí ${birdCount(task.base)}. Potom do lesa odletí ${birdCount(task.away)}. Který zápis vypráví totéž?</p>`;choices([`${task.base} − ${task.away}`,`${task.base} + ${task.away}`],i=>{route=i;if(i===0)advance();else{message(`Zkus přemýšlet, co říká plus. Znamenalo by, že další sýkorky přiletěly. Ty naše ale odletěly.`,true);action('Vrátit se k sýkorkám',()=>{stage=1;render()})}})}else{work.innerHTML='<p class="instruction">Ke stejnému výsledku může vést více cest. Vyber tu, které rozumíš. Můžeš se k rozcestí vrátit.</p>';choices(task.paths,i=>{route=i;advance()})}}
if(stage===3){title(w===0?'Zkontroluj svůj příběh.':'Vyzkoušej vybranou cestu.');if(w===0){work.innerHTML=`<div class="math-line">${task.base} − ${task.away} = <span>?</span></div><p class="instruction">Když některé sýkorky odletí, bude jich na větvi méně, nebo více?</p>`;choices(['Méně než na začátku.','Více než na začátku.'],i=>i===0?advance():message('Podívej se na sýkorky, které odletěly. Na větvi po nich zůstalo volné místo.',true))}else if(!task.valid.includes(route)){work.innerHTML=`<p>${esc(task.paths[route])}</p><label for="trial">Zkus si tuto cestu dopočítat. Co ti vyšlo?</label><input id="trial" class="number" inputmode="decimal"><div id="trial-result"></div>`;action('Porovnat s příběhem',()=>{const raw=document.getElementById('trial').value.trim();if(!raw){message('Napiš nejdřív svůj pokusný výsledek. Můžeš se také rovnou vrátit.',true);return}document.getElementById('trial-result').innerHTML=`<div class="note"><b>Tvůj pokus: ${esc(raw)}</b><p>${esc(task.explain[route])}</p></div>`;tone(false)});action('Vybral jsem jinou cestu. Zpět na rozcestí.',back)}else{work.innerHTML=`<p>${esc(task.explain[route])}</p>`;routeTool();action('Zpět na rozcestí',back)}}
if(stage===4){title('Výpočet je bonus navíc.');work.innerHTML=`<p class="instruction">${w===0?'Příběh jsi ukázal správně. Chceš ještě spočítat sýkorky, které zůstaly?':'Rozumíš situaci a sestavil jsi správný postup. Můžeš ho teď dopočítat.'}</p><label for="answer">${w===0?'Kolik sýkorek zůstalo?':`Výsledek (${esc(task.unit)})`}</label><input id="answer" class="number" inputmode="decimal" value="${esc(answerDraft)}"><p class="small-note">Pokračovat můžeš i bez výpočtu.</p>`;action('Zkontrolovat výsledek',()=>{const raw=document.getElementById('answer').value.trim(),n=Number(raw.replace(',','.'));answerDraft=raw;if(raw&&Number.isFinite(n)&&Math.abs(n-task.answer)<.0001){bonus=true;advance();tone(true)}else message('Příběhu rozumíš a postup máš správný. Ve výpočtu ještě něco nesedí. Zkus ho opravit, nebo pokračuj bez bonusu.',true)},true);action('Pokračovat bez výpočtu',advance);document.getElementById('answer').onkeydown=e=>{if(e.key==='Enter')document.querySelector('#actions button').click()}}
if(stage===5){title(w===0?'Sýkorky ti děkují.':'Je to možné i ve skutečnosti?');if(w===0){complete();return}choices([task.badcheck,task.check],i=>{if(i===1)complete();else message('Jak by tato kontrola odhalila chybu? Vyber kontrolu, která opravdu odpovídá příběhu.',true)})}
if(stage===6){title('Další kousek světa je tvůj.');work.innerHTML=`<p class="instruction">${w===0?'Ukázal jsi, co se stalo se sýkorkami, a spojil jsi příběh se správným zápisem.':'Porozuměl jsi otázce, vybral jsi postup a ověřil jeho význam.'}</p><div class="reward"><span class="sprite plank"></span><span class="sprite plank"></span><span class="sprite plank"></span></div><p>${celebrate?'Tři prkénka přibyla ke krmítku.':'Tento úkol už máš splněný. Krmítko na tebe čeká v dalším novém příběhu.'} ${bonus?'Za správný výpočet zazněla navíc slavnostní melodie.':''}</p><p class="small-note">${w===0&&done(0).length===10?'Prvních deset úkolů je hotovo. První část háje se vybarvila.':'Po deseti různých úkolech se vybarví první část světa.'}</p>`;if(w===0&&mission<9)action('Další příběh',()=>enter(0,mission+1),true);action('Zpět na mapu',map);action('Zkusit tento příběh znovu',()=>enter(w,mission))}
}
function complete(){if(!done(w).includes(mission)){progress[w]=[...done(w),mission];persist();celebrate=true}else celebrate=false;stage=6;render();tone(true)}
function birdBoard(){const task=t(),work=document.getElementById('work');work.innerHTML=`<p class="instruction">Do lesa odletí ${birdCount(task.away)}. Sýkorku přetáhneš z větve do lesa. Můžeš na ni také klepnout.</p><div class="bird-habitat" id="branch-zone"><span class="zone-label">NA VĚTVI</span><div class="birds" id="branch"></div></div><div class="bird-habitat forest-zone" id="forest-zone"><span class="zone-label">V LESE</span><div class="birds" id="forest"></div></div><p class="small-note">Sýkorku vrátíš klepnutím na ni v lese.</p>`;
for(let i=0;i<task.base;i++){const b=document.createElement('button');b.className='bird-token';b.innerHTML='<span class="sprite bird"></span>';b.setAttribute('aria-label',`${moved.has(i)?'Vrátit':'Nechat odletět'} sýkorku ${i+1}`);b.draggable=true;b.ondragstart=e=>e.dataTransfer.setData('text/plain',String(i));b.onclick=()=>{if(moved.has(i))moved.delete(i);else moved.add(i);render()};document.getElementById(moved.has(i)?'forest':'branch').append(b)}
for(const dest of ['branch','forest']){const el=document.getElementById(dest+'-zone');el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();const raw=e.dataTransfer.getData('text/plain'),i=Number(raw);if(raw!==''&&Number.isInteger(i)&&i>=0&&i<task.base){if(dest==='forest')moved.add(i);else moved.delete(i);render()}}}
action('Takto se to stalo',()=>{if(moved.size===task.away){advance();tone(true)}else message(moved.size>task.away?`V lese je teď více sýkorek, než říká příběh. Některé vrať na větev.`:`V příběhu do lesa odletí ${birdCount(task.away)}. Zkus příběh ještě dokončit.`,true)},true)}
function groupBoard(){const target=w===1?3:4,work=document.getElementById('work');work.innerHTML=`<p class="instruction">${w===1?'Připrav pro každé dítě tři rohlíky. Tlačítkem přidáš jeden rohlík na jeho talíř.':'Na každý záhon umísti čtyři sazenice rajčat. Tlačítkem přidáš jednu sazenici.'}</p><div class="group-grid">${groups.map((n,i)=>`<div class="group"><b>${w===1?['Anička','Tomáš','Ema','Petr'][i]:`Záhon ${i+1}`}</b><div class="group-items">${Array.from({length:n},()=>`<span class="object ${w===1?'roll':'seedling'}" role="img" aria-label="${w===1?'rohlík':'sazenice rajčete'}"></span>`).join('')}</div><div class="group-buttons"><button data-minus="${i}" aria-label="Odebrat jednu položku ze skupiny ${i+1}">−</button><span>${n}</span><button data-plus="${i}" aria-label="Přidat jednu položku do skupiny ${i+1}">+</button></div></div>`).join('')}</div>`;work.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{groups[+b.dataset.plus]=Math.min(8,groups[+b.dataset.plus]+1);render()});work.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{groups[+b.dataset.minus]=Math.max(0,groups[+b.dataset.minus]-1);render()});action('Příběh je připravený',()=>{if(groups.every(n=>n===target)){advance();tone(true)}else message(w===1?'Podívej se na každý talíř zvlášť. Má každé dítě právě tři rohlíky?':'Podívej se na každý záhon zvlášť. Rostou na každém právě čtyři sazenice rajčat?',true)},true)}
function routeTool(){const task=t(),work=document.getElementById('work');
if(w===8){work.innerHTML+=`<div class="tariff-tool"><label for="minutes">Vyzkoušej počet minut</label><input id="minutes" type="range" min="0" max="100" step="10" value="${modelValue||0}"><div id="tariff-values"></div></div><p>Co znamená hledaný bod, kde se ceny setkají?</p>`;const update=()=>{const n=+document.getElementById('minutes').value;modelValue=String(n);document.getElementById('tariff-values').innerHTML=`<strong>${n} minut</strong><div class="price-row"><b>A</b><div class="price-bar" style="width:${(100+4*n)/5}%">${100+4*n} Kč</div></div><div class="price-row"><b>B</b><div class="price-bar b" style="width:${(200+2*n)/5}%">${200+2*n} Kč</div></div>`};document.getElementById('minutes').oninput=update;update();choices(['Stejný počet minut vede u obou nabídek ke stejné celkové ceně.','Obě nabídky mají stejný měsíční poplatek.'],i=>i===0?advance():message('Měsíční poplatky se nemění. Hledáme shodu celkových cen za stejný počet minut.',true));return}
const prompts={1:['Který zápis odpovídá tvým talířům?',route===0?['4 × 3','4 + 3']:['3 + 3 + 3 + 3','4 + 4 + 4 + 4'],0],2:['Který zápis odpovídá šesti záhonům?',route===0?['6 × 4','6 + 4']:['(3 × 4) × 2','3 × 4 + 2'],0],3:['Které jednotky bude mít výsledek?', ['metry čtvereční — měříme plochu.','metry — měříme délku plotu.'],1],4:['Čím vydělíš objem vody, abys získal výšku?', ['Obsahem dna.','Obvodem dna.'],0],5:['Po vynásobení 8 × 25 000 získáš…',['délku ve skutečnosti v centimetrech.','délku ve skutečnosti v kilometrech.'],0],6:['Úsporu 120 kWh porovnáváš s…',['800 kWh, protože to byla původní spotřeba.','680 kWh, protože to je nová spotřeba.'],0],7:['Kterou stranu trojúhelníku představuje žebřík?',['Nejdelší stranu proti pravému úhlu.','Vodorovnou stranu podél země.'],0]};
if(w===4){work.innerHTML+=`<div class="water-tool"><label for="litres">Prozkoumej: kolik vody nalijeme?</label><input id="litres" type="range" min="0" max="200" step="5" value="${modelValue||0}"><div class="water-tank"><div id="water-fill"></div><span id="water-label"></span></div><small>Dno: 100 × 40 cm · výška nádrže: 50 cm</small></div>`;const update=()=>{const v=+document.getElementById('litres').value;modelValue=String(v);document.getElementById('water-fill').style.height=v/2+'%';document.getElementById('water-label').textContent=`${v} litrů · hladina ${(v/4).toLocaleString('cs-CZ')} cm`};document.getElementById('litres').oninput=update;update()}
const [q,a,ok]=prompts[w];const p=document.createElement('p');p.textContent=q;work.append(p);choices(a,i=>i===ok?advance():message('Vrať se k významu veličin v příběhu. '+(w===4?'Voda pokrývá celé dno, ne jen jeho okraj.':'Zkus si zvolený údaj nebo zápis vysvětlit vlastními slovy.'),true))}
function showHint(){hint++;const task=t();let text;if(w===0){text=stage<=1?(hint===1?'Poslechni si příběh ještě jednou. Které sýkorky zůstaly a které odletěly?':`Do lesa patří ${birdCount(task.away)}. Ostatní mají zůstat na větvi.`):'Když sýkorky odletěly, ptáků na větvi ubylo. Ubrání zapisujeme znaménkem minus.'}else if(stage<=1){text=w===1?'Neřeš zatím všechny rohlíky najednou. Připrav nejprve tři pro Aničku. Potom stejnou svačinu pro ostatní.':w===2?'Začni jedním záhonem. Mají na něm růst čtyři sazenice rajčat. Potom připrav stejně i ostatní záhony.':hint===1?'Řekni vlastními slovy, co máme zjistit. Které údaje k tomu potřebuješ?':tasks[w].model}else text=hint===1?'Zkus si vybranou cestu nakreslit nebo ji popsat nahlas. Můžeš se vrátit na rozcestí.':`Použít můžeš obě tyto cesty: ${task.paths[0]} Nebo: ${task.paths[1]}`;document.getElementById('help').innerHTML=`<aside class="note">${esc(text)}</aside>`;say(text)}
document.getElementById('home').onclick=map;document.getElementById('sound').onclick=()=>{sound=!sound;const b=document.getElementById('sound');b.textContent=sound?'♫ Zvuk zapnutý':'♫ Zvuk vypnutý';b.setAttribute('aria-pressed',String(sound))};map();
