'use strict';
const worldNames=['Ptačí háj','Tržní přístav','Údolí dílen','Město mostů','Jezerní laboratoř','Horská železnice','Energetické město','Inženýrská stanice','Rada budoucnosti'];
const subtitles=['Malé příběhy mezi větvemi','Svačina pro všechny','Co roste na zahradě','Zahrada u nového mostu','Kolik místa potřebuje voda','Z mapy do skutečných hor','Co znamená úspora','Cesta k hvězdárně','Rozhodnutí, která dávají smysl'];
const stories=[
['Na větvi sedí 6 sýkorek.','2 sýkorky odletí do lesa.'],
['Chystáme svačinu pro 4 děti.','Každé dítě dostane 3 rohlíky.'],
['Na zahradě máme 6 záhonů.','Na každém záhonu rostou 4 sazenice rajčat.'],
['U domu je obdélníková zahrada. Je dlouhá 8 metrů a široká 5 metrů.','Kolem zahrady chceme postavit plot. Na jedné straně bude branka široká 2 metry. V místě branky plot nebude.'],
['Chceme nalít vodu do prázdného akvária. Jeho vnitřní délka je 100 cm, šířka 40 cm a výška 50 cm.','Do akvária nalijeme 65 litrů vody. Není v něm písek ani žádné dekorace.'],
['Plánujeme výlet vlakem. Na mapě měří vybraná trať 8 cm.','Mapa má měřítko 1 : 25 000. To znamená, že 1 cm na mapě představuje 25 000 cm ve skutečnosti.'],
['Veřejné osvětlení dříve spotřebovalo každý den 800 kWh elektrické energie.','Po výměně lamp spotřebuje za den 680 kWh. Chceme porovnat úsporu s původní spotřebou.'],
['U hvězdárny je plošina ve výšce 4 metry nad vodorovnou zemí. Stěna pod plošinou je svislá.','K plošině přistavíme žebřík. Jeho dolní konec bude na zemi 3 metry od stěny.'],
['Vybíráme mezi dvěma nabídkami telefonního operátora. U nabídky A zaplatíme každý měsíc 100 Kč a k tomu 4 Kč za každou provolanou minutu.','U nabídky B zaplatíme každý měsíc 200 Kč a k tomu 2 Kč za každou provolanou minutu. Žádné další poplatky nepočítáme.']
];
const questions=['Kolik sýkorek zůstane na větvi?','Kolik rohlíků potřebujeme pro všechny 4 děti?','Kolik sazenic rajčat roste na celé zahradě?','Kolik metrů plotu potřebujeme?','Jak vysoko bude sahat voda ode dna akvária?','Jak dlouhá je trať ve skutečnosti? Odpověz v kilometrech.','O kolik procent původní spotřeby se spotřeba snížila?','Jak dlouhý musí být žebřík, aby dosáhl přesně k plošině?','Při kolika provolaných minutách zaplatíme za obě nabídky stejnou částku?'];
tasks.forEach((t,i)=>{t.story=stories[i];t.question=questions[i]});
tasks[1].model='4 děti. Každému dítěti patří 3 rohlíky.';
tasks[2].model='6 záhonů. Na každém záhonu rostou 4 sazenice rajčat.';
tasks[8].paths=['Zapíšu obě celkové ceny a najdu, kdy se rovnají.','Zjistím, za kolik minut se vyrovná rozdíl měsíčních poplatků.','Porovnám jen měsíční poplatky. Nabídka A bude vždy levnější.'];
tasks[8].explain=['Označím počet minut písmenem x. Celkové ceny jsou 100 + 4x a 200 + 2x. Hledám takové x, při kterém jsou stejné.','U B zaplatím každý měsíc o 100 Kč více. Za každou minutu ale ušetřím 2 Kč. Hledám, za kolik minut ušetřím právě těch 100 Kč.','Při 100 minutách zaplatím za A 500 Kč a za B 400 Kč. Samotný měsíční poplatek tedy nestačí k rozhodnutí.'];
const birdMissions=[[6,2],[5,1],[7,3],[8,2],[6,3],[9,4],[7,2],[8,5],[10,4],[9,3]];
const KEY='fajn-rozumim-v2';
const CITY_GRADES={0:{modelKey:'grade1Model',worldKey:'grade1World',storageKey:'fajn-rozumim-grade1-v1',title:'Barevná vesnička',eyebrow:'BAREVNÁ VESNIČKA'},1:{modelKey:'grade2Model',worldKey:'grade2World',storageKey:'fajn-rozumim-grade2-v1',title:'Pohádkové městečko',eyebrow:'POHÁDKOVÉ MĚSTEČKO'},2:{modelKey:'grade3Model',worldKey:'grade3World',storageKey:'fajn-rozumim-grade3-v1',title:'Hravé město',eyebrow:'HRAVÉ MĚSTO'},3:{modelKey:'grade4Model',worldKey:'grade4World',storageKey:'fajn-rozumim-grade4-v1',title:'Výpravné město',eyebrow:'VÝPRAVNÉ MĚSTO'},4:{modelKey:'grade5Model',worldKey:'grade5World',storageKey:'fajn-rozumim-grade5-v1',title:'Dobrodružné město',eyebrow:'DOBRODRUŽNÉ MĚSTO'},5:{modelKey:'grade6Model',worldKey:'grade6World',storageKey:'fajn-rozumim-grade6-v1',title:'Objevné město',eyebrow:'OBJEVNÉ MĚSTO'},6:{modelKey:'grade7Model',worldKey:'grade7World',storageKey:'fajn-rozumim-grade7-v1',title:'Souměrné město',eyebrow:'SOUMĚRNÉ MĚSTO'},7:{modelKey:'grade8Model',worldKey:'grade8World',storageKey:'fajn-rozumim-grade8-v1',title:'Konstrukční město',eyebrow:'KONSTRUKČNÍ MĚSTO'},8:{modelKey:'grade9Model',worldKey:'grade9World',storageKey:'fajn-rozumim-grade9-v1',title:'Město souvislostí',eyebrow:'MĚSTO SOUVISLOSTÍ',legacyTopicId:'finance'}};
function isCity(w){return !!CITY_GRADES[w]}
function cityModel(w){return window[CITY_GRADES[w].modelKey]}
function cityWorld(w){return window[CITY_GRADES[w].worldKey]}
let progress={},cityProgress={};
try{const raw=localStorage.getItem(KEY);const p=JSON.parse(raw||'{}');if(p&&typeof p==='object'&&!Array.isArray(p))progress=p;if(!raw){const old=JSON.parse(localStorage.getItem('fajn-rozumim-v1')||'{}');if(Array.isArray(old.completed))old.completed.forEach(i=>{if(Number.isInteger(i)&&i>=0&&i<9)progress[i]=[0]})}
 for(const cw of Object.keys(CITY_GRADES).map(Number)){const cfg=CITY_GRADES[cw],model=cityModel(cw),saved=JSON.parse(localStorage.getItem(cfg.storageKey)||'null');if(Array.isArray(saved))cityProgress[cw]=saved.filter(id=>model.tasks.some(t=>t.id===id));else{cityProgress[cw]=(Array.isArray(progress[cw])?progress[cw]:[]).filter(Number.isInteger).map(i=>model.tasks.find(t=>t.missionIndex===i&&t.available)?.id).filter(Boolean);localStorage.setItem(cfg.storageKey,JSON.stringify(cityProgress[cw]))}}
}catch{}
let w=0,mission=0,stage=0,sound=true,moved=new Set(),groups=[],route=null,bonus=false,hint=0,feedbackText='',feedbackBad=false,modelValue='',selected=null,answerDraft='',celebrate=false,selectedCityTaskId={};
const app=document.getElementById('app');const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function done(i){return Array.isArray(progress[i])?progress[i].filter(n=>Number.isInteger(n)&&n>=0&&n<10):[]}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(progress));for(const cw of Object.keys(CITY_GRADES).map(Number))localStorage.setItem(CITY_GRADES[cw].storageKey,JSON.stringify(cityProgress[cw]))}catch{feedbackText='Pokrok se nepodařilo uložit. Prohlížeč nepovoluje ukládání.'}}
function birdCount(n){return `${window.csNumber(n,'f')} ${n===1?'sýkorka':n<5?'sýkorky':'sýkorek'}`}
function birdAcc(n){return `${window.csNumber(n,'f',true)} ${n===1?'sýkorku':n<5?'sýkorky':'sýkorek'}`}
function cityTask(w){const model=cityModel(w);return model.tasks.find(task=>task.id===selectedCityTaskId[w])||model.tasks.find(task=>task.topicId===model.topics[0].id&&task.topicOrder===1)}
function t(){if(isCity(w)){const meta=cityTask(w);if(meta?.content)return meta.content;return window.makeMission(w,meta?.missionIndex??mission,tasks[w])}if(w)return window.makeMission(w,mission,tasks[w]);const [n,k]=birdMissions[mission];return {...tasks[0],story:[`Na větvi sedí ${birdCount(n)}.`,`Do lesa odletí ${birdCount(k)}.`],answer:n-k,base:n,away:k}}
let soundIndex=-1,lastError=-Infinity;
function tone(ok,bonus=false){if(!sound)return;if(!ok&&Date.now()-lastError<1800)return;if(!ok)lastError=Date.now();try{const c=new AudioContext();const tunes=[[523,659,784],[587,740,880],[659,784,988],[523,784],[698,880,1047]];if(ok)soundIndex=(soundIndex+1)%tunes.length;const notes=ok?tunes[soundIndex]:[262,247];notes.forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain(),at=c.currentTime+i*.09;o.type=ok?'sine':'triangle';o.frequency.value=f*(bonus?1.12:1);g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(ok?.025:.012,at+.015);g.gain.exponentialRampToValueAtTime(.0001,at+.15);o.connect(g).connect(c.destination);o.start(at);o.stop(at+.17)});setTimeout(()=>c.close(),600)}catch{}}
let narration=null;
function deviceVoice(text){stopVoice();if(!('speechSynthesis'in window)){message('Tento prohlížeč neumí text přečíst.');return}const u=new SpeechSynthesisUtterance(text);u.lang='cs-CZ';u.rate=w<3?.82:.95;speechSynthesis.speak(u)}
function say(text){stopVoice();const meta=isCity(w)?cityTask(w):null,voiceMission=meta?.missionIndex??mission;const entry=meta?.content?null:window.voiceManifest?.[`${w}-${voiceMission}`];const help=document.getElementById('help');const fallback=()=>{help.innerHTML='<aside class="note">Namluvená verze tohoto příběhu zatím není dostupná. Můžeš si zapnout hlas svého zařízení.<br><button id="device-voice" class="action">Přečíst hlasem zařízení</button></aside>';document.getElementById('device-voice').onclick=()=>deviceVoice(text)};
if(!entry||entry.text!==text){fallback();return}help.innerHTML='<p class="small-note">Posloucháš hlas vytvořený umělou inteligencí. <button id="stop-voice" class="read-button">Zastavit</button></p>';document.getElementById('stop-voice').onclick=stopVoice;narration=new Audio(entry.src);narration.onended=()=>{narration=null};narration.onerror=fallback;narration.play().catch(fallback)}
function stopVoice(){if(narration){narration.pause();narration=null}if('speechSynthesis'in window)speechSynthesis.cancel()}
function message(s,bad=false){feedbackText=s;feedbackBad=bad;const el=document.getElementById('feedback');if(el){el.textContent=s;el.classList.toggle('bad',bad)}if(bad)tone(false)}
function art(i,cls=''){return `<div class="world-art ${cls}" style="--x:${i%3*50}%;--y:${Math.floor(i/3)*50}%" aria-hidden="true"></div>`}
function map(){document.onkeydown=null;stopVoice();app.innerHTML=`<section class="map-intro"><span class="eyebrow">TVOJE VÝPRAVA</span><h1>Devět světů čeká na svůj příběh.</h1><p>Začni v kterémkoli ročníku. Barvy do světa vracejí až dokončené úkoly.</p></section><section class="world-grid" aria-label="Vyber ročník">${worldNames.map((name,i)=>{const count=isCity(i)?cityProgress[i].length:done(i).length,available=isCity(i)?cityModel(i).tasks.filter(t=>t.available).length:10,reveal=Math.floor(count/10)*10;return `<button class="world-card" data-world="${i}"><div class="world-picture">${art(i,'gray')}${art(i,'color')}<div class="reveal-mask" style="--revealed:${reveal}%"></div><span class="grade">${i+1}<small>ROČNÍK</small></span><span class="enter-label">Vstoupit ↗</span></div><div class="world-copy"><h2>${name}</h2><p>${subtitles[i]}</p><div class="progress-track"><i style="width:${Math.min(100,count)}%"></i></div><small>${count} / ${available} dostupných úloh · ${count?'Výprava začala':'Vstup je volný'}</small></div></button>`}).join('')}</section><footer>Nyní je připraveno 900 úloh: všech devět ročníků má sto úloh. Každý ročník má deset tematických okruhů po deseti úlohách. Pokrok zůstává v tomto prohlížeči.</footer>`;app.querySelectorAll('[data-world]').forEach(b=>{const i=+b.dataset.world,count=isCity(i)?cityProgress[i].length:done(i).length;b.querySelector('.color').style.clipPath=`inset(0 ${100-Math.floor(count/10)*10}% 0 0)`;b.onclick=()=>isCity(i)?cityOverview(i):enter(i)})}
let selTopic={},selFilter={};
function cityDone(w,task){return cityProgress[w].includes(task.id)}
function cityVisibleTasks(w){const topic=selTopic[w]||'all',filter=selFilter[w]||'all';return cityModel(w).tasks.filter(t=>(topic==='all'||t.topicId===topic)&&(filter==='all'||(filter==='done'&&cityDone(w,t))||(filter==='todo'&&!cityDone(w,t))))}
function cityOverview(gw){
 document.onkeydown=null;stopVoice();w=gw;
 const cfg=CITY_GRADES[gw],{topics,tasks:allTasks}=cityModel(gw),world=cityWorld(gw),topic=selTopic[gw]||'all',filter=selFilter[gw]||'all',shown=cityVisibleTasks(gw);
 app.innerHTML=`<nav class="crumb"><button id="map-back">← Mapa světů</button><span>${gw+1}. ročník <b>/</b> ${cfg.title}</span><span>${cityProgress[gw].length} / 100 splněno</span></nav>${world.render(cityProgress[gw],topic)}<section class="task-overview" id="task-overview"><div class="overview-heading"><div><span class="eyebrow">VYBER SI, CO PRÁVĚ POTŘEBUJEŠ</span><h2>${topic==='all'?'Všechny matematické okruhy':esc(topics.find(t=>t.id===topic)?.name)}</h2><p>Úlohy můžeš řešit v libovolném pořadí. Hotovou úlohu lze kdykoli procvičit znovu.</p></div></div><div class="topic-summary">${topics.map(tp=>{const count=allTasks.filter(t=>t.topicId===tp.id&&cityDone(gw,t)).length;return `<button data-summary-topic="${tp.id}" class="${topic===tp.id?'active':''}"><b>${esc(tp.name)}</b><span>${count} / 10</span></button>`}).join('')}</div><div class="overview-controls"><label>Matematický okruh<select id="topic-filter"><option value="all">Všechny okruhy</option>${topics.map(t=>`<option value="${t.id}" ${topic===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><fieldset><legend>Stav úloh</legend>${[['all','Všechny'],['todo','Nesplněné'],['done','Splněné']].map(([v,n])=>`<button class="filter-button ${filter===v?'active':''}" data-filter="${v}" aria-pressed="${filter===v}">${n}</button>`).join('')}</fieldset><button id="reset-topic" class="reset-button" ${topic==='all'?'disabled title="Nejprve vyber jeden okruh"':''}>Vynulovat tento okruh</button></div><div class="task-list" aria-live="polite">${shown.length?shown.map(task=>`<article class="task-card ${cityDone(gw,task)?'done':''}"><div><span class="task-number">${task.topicOrder}</span><span><b>${esc(task.title)}</b><small>${esc(task.topic)} · ${esc(task.difficulty)} obtížnost</small></span></div><button data-task-id="${task.id}">${cityDone(gw,task)?'Procvičit znovu':'Otevřít úlohu'}</button></article>`).join(''):'<p class="empty-list">Tomuto filtru neodpovídá žádná úloha.</p>'}</div></section>`;
 document.getElementById('map-back').onclick=map;
 const chooseTopic=id=>{selTopic[gw]=id;cityOverview(gw);setTimeout(()=>document.getElementById('task-overview')?.scrollIntoView({behavior:'smooth'}),0)};
 app.querySelectorAll('[data-city-topic],[data-summary-topic]').forEach(b=>b.onclick=()=>chooseTopic(b.dataset.cityTopic||b.dataset.summaryTopic));
 const select=document.getElementById('topic-filter');select.onchange=()=>chooseTopic(select.value);
 app.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{selFilter[gw]=b.dataset.filter;cityOverview(gw)});
 app.querySelectorAll('[data-task-id]').forEach(b=>b.onclick=()=>enter(gw,b.dataset.taskId));
 document.getElementById('reset-topic').onclick=()=>resetCityTopic(gw);window.scrollTo?.({top:0,behavior:'instant'})
}
function resetCityTopic(gw){const topic=selTopic[gw];if(!topic||topic==='all')return;const model=cityModel(gw),tp=model.topics.find(t=>t.id===topic);if(!tp||!confirm(`Opravdu vynulovat všechny splněné úlohy v okruhu „${tp.name}“? Pokrok v ostatních okruzích zůstane zachován.`))return;const ids=new Set(model.tasks.filter(x=>x.topicId===topic).map(x=>x.id));const missions=new Set(model.tasks.filter(x=>x.topicId===topic&&x.available).map(x=>x.missionIndex));cityProgress[gw]=cityProgress[gw].filter(id=>!ids.has(id));progress[gw]=done(gw).filter(i=>!missions.has(i));persist();cityOverview(gw)}
function nextMission(){for(let step=1;step<=10;step++){const n=(mission+step)%10;if(!done(w).includes(n))return n}return null}
function enter(i,m){if(isCity(i)&&m===undefined){cityOverview(i);return}document.onkeydown=null;stopVoice();w=i;if(isCity(i)){const model=cityModel(i),cfg=CITY_GRADES[i],meta=typeof m==='string'?model.tasks.find(task=>task.id===m):model.tasks.find(task=>task.topicId===cfg.legacyTopicId&&task.missionIndex===(m??0));const resolved=meta??model.tasks.find(t=>t.topicId===model.topics[0].id&&t.topicOrder===1);selectedCityTaskId[i]=resolved?.id;mission=resolved?resolved.missionIndex??resolved.topicOrder-1:0}else mission=m??Math.max(0,Array.from({length:10},(_,n)=>n).findIndex(n=>!done(i).includes(n)));stage=0;moved=new Set();groups=Array(!isCity(i)&&(i===1||i===2)?t().n:0).fill(0);route=null;bonus=false;hint=0;modelValue='';selected=null;answerDraft='';feedbackText='';celebrate=false;render();window.scrollTo?.({top:0,behavior:'instant'})}
function advance(){stage++;hint=0;feedbackText='';selected=null;render()}
function previousStep(){if(stage<=0||stage>=6)return;stage--;hint=0;feedbackText='';feedbackBad=false;selected=null;render()}
function back(){stage=(!isCity(w)&&w===0)?1:2;route=null;feedbackText='Můžeš zkusit jinou cestu. Tvoje představa zůstává zachovaná.';render()}
function action(label,fn,primary=false){const b=document.createElement('button');b.className='action'+(primary?' primary':'');b.textContent=label;b.onclick=fn;document.getElementById('actions').append(b);return b}
function choices(items,fn){const box=document.createElement('div');box.className='choices';items.forEach((s,i)=>{const b=document.createElement('button');b.className='choice';b.innerHTML=`<span class="choice-index">${String.fromCharCode(65+i)}</span><span>${esc(s)}</span>`;b.onclick=()=>fn(i);box.append(b)});document.getElementById('work').append(box)}
function render(){const task=t(),meta=isCity(w)?cityTask(w):null,cfg=isCity(w)?CITY_GRADES[w]:null,count=isCity(w)?cityProgress[w].filter(id=>cityModel(w).tasks.find(x=>x.id===id)?.topicId===meta?.topicId).length:done(w).length,finished=isCity(w)?cityDone(w,meta):done(w).includes(mission),chapter=isCity(w)?Math.floor(cityProgress[w].length/10):Math.floor(count/10),taskNumber=meta?.topicOrder??mission+1;app.innerHTML=`<nav class="crumb"><button id="map-back">${isCity(w)?'← Herní svět a úlohy':'← Mapa světů'}</button><span>${w+1}. ročník <b>/</b> ${isCity(w)?cfg.title:worldNames[w]}</span><span>${isCity(w)?esc(meta.topic):'Úkol'} ${taskNumber} z 10</span></nav><section class="play-layout"><div class="story-side"><div class="scene ${celebrate?'celebrate':''}">${art(w,'gray')}${art(w,'color')}<div class="scene-shade"></div><div class="scene-title"><span class="eyebrow">${isCity(w)?cfg.eyebrow:w===0?'PŘÍBĚHY Z VĚTVE':'MALÁ VÝPRAVA'}</span><h1>${isCity(w)?cityWorld(w).districts[meta.topicId].name:worldNames[w]}</h1></div><div class="scene-status">${isCity(w)?`${count} z 10 prvků čtvrti žije`:chapter?`${chapter}. část světa ožila`:'Svět čeká na první dokončenou desítku'}</div></div><article class="story-paper"><div class="story-heading"><span class="eyebrow">POSLECHNI SI PŘÍBĚH</span><button id="read" class="read-button" aria-label="Přečíst příběh">♫ Přečíst</button></div>${task.story.map(s=>`<p>${esc(s)}</p>`).join('')}<p class="question">${esc(task.question)}</p></article>${isCity(w)?cityWorld(w).mini(meta.topicId,cityProgress[w],meta.topicOrder):`<section class="construction"><div><span class="eyebrow">TVÁ STAVBA</span><h3>${w===0?'Krmítko pro sýkorky':'První krmítko v novém světě'}</h3><p>${count} / 10 stavebních kroků</p></div><div class="feeder"><div class="sprite unfinished"></div><div class="sprite finished" style="clip-path:inset(${100-Math.min(100,count*10)}% 0 0 0)"></div></div>${celebrate?'<div class="flying-planks"><i class="sprite plank"></i><i class="sprite plank"></i><i class="sprite plank"></i></div>':''}</section>`}</div><article class="activity"><div class="step-dots">${['Příběh','Představa','Postup','Ověření'].map((s,i)=>`<span class="${i<=Math.min(3,stage)?'active':''}">${i+1}<small>${s}</small></span>`).join('')}</div><div class="activity-heading"><h2 id="title"></h2><button id="hint" class="hint-button">? Pomoc</button></div><div id="help"></div><div id="work"></div><div id="feedback" class="feedback ${feedbackBad?'bad':''}" role="status">${esc(feedbackText)}</div><div id="actions" class="actions"></div></article></section>`;
app.querySelector('.scene .color').style.clipPath=`inset(0 ${100-chapter*10}% 0 0)`;
document.getElementById('map-back').onclick=isCity(w)?()=>cityOverview(w):map;document.getElementById('read').onclick=()=>say(window.spokenStory(task));document.getElementById('hint').onclick=showHint;
const title=s=>document.getElementById('title').textContent=s,work=document.getElementById('work');
if(stage===0){title(!isCity(w)&&w===0?'Podívej se na sýkorky.':'Co potřebujeme zjistit?');if(!isCity(w)&&w===0){work.innerHTML=`<p class="instruction">Tady sedí všechny sýkorky. V dalším kroku necháš dvě odletět.</p><div class="bird-preview">${Array.from({length:task.base},()=>'<span class="sprite bird"></span>').join('')}</div>`;work.querySelector('p').textContent=`Tady sedí všechny sýkorky. V dalším kroku necháš odletět ${birdAcc(task.away)}.`;action('Ukázat, co se stalo',advance,true)}else{const correctFirst=w%2===0;choices(correctFirst?[task.question,task.other]:[task.other,task.question],i=>{if(i===(correctFirst?0:1)){advance();}else message('Tato otázka se ptá na něco jiného. Přečti si znovu poslední větu příběhu.',true)})}}
if(stage===1){title((!isCity(w)&&w===0)?'Nech sýkorky odletět.':(!isCity(w)&&w<3)?'Sestav si celý příběh.':'Co znamenají údaje?');if(!isCity(w)&&w===0)birdBoard();else if(!isCity(w)&&w<3)groupBoard();else{const models=[null,null,null,{q:'Plot povede…',a:['po okraji zahrady, s volným místem pro branku.','po celé ploše zahrady jako trávník.'],ok:0},{q:'Voda v akváriu…',a:['vyplní celé dno a vytvoří nad ním vrstvu.','bude tvořit jen úzký sloupec u jedné stěny.'],ok:0},{q:`Údaj ${task.n} cm označuje…`,a:['délku skutečné železniční tratě.','délku čáry, která představuje trať na mapě.'],ok:1},{q:'Sto procent v této úloze představuje…',a:[`novou spotřebu ${task.left} kWh.`,`původní spotřebu ${task.base} kWh.`],ok:1},{q:'Žebřík v tomto příběhu…',a:['spojuje dolní konec na zemi přímo s plošinou.','vede nejprve po zemi a potom svisle podél zdi.'],ok:0},{q:'Celková měsíční cena se skládá…',a:['jen z ceny za jednu minutu.','z měsíčního poplatku a ceny všech provolaných minut.'],ok:1}][w],model=task.modelChoice||models;work.innerHTML=`<p class="instruction">${model.q}</p>`;choices(model.a,i=>{if(i===model.ok){advance();}else message('Zkus si situaci představit vlastními slovy. Která možnost popisuje právě náš příběh?',true)})}}
if(stage===2){title((!isCity(w)&&w===0)?'Jak zapíšeme odlet?':'Na rozcestí si vyber cestu.');if(!isCity(w)&&w===0){work.innerHTML=`<p class="instruction">Na začátku na větvi sedí ${birdCount(task.base)}. Potom do lesa odletí ${birdCount(task.away)}. Který zápis vypráví totéž?</p>`;choices([`${task.base} − ${task.away}`,`${task.base} + ${task.away}`],i=>{route=i;if(i===0)advance();else{message(`Zkus přemýšlet, co říká plus. Znamenalo by, že další sýkorky přiletěly. Ty naše ale odletěly.`,true);action('Vrátit se k sýkorkám',()=>{stage=1;render()})}})}else{work.innerHTML='<p class="instruction">Ke stejnému výsledku může vést více cest. Vyber tu, které rozumíš. Můžeš se k rozcestí vrátit.</p>';choices(task.paths,i=>{route=i;advance()})}}
if(stage===3){title((!isCity(w)&&w===0)?'Zkontroluj svůj příběh.':'Vyzkoušej vybranou cestu.');if(!isCity(w)&&w===0){work.innerHTML=`<div class="math-line">${task.base} − ${task.away} = <span>?</span></div><p class="instruction">Když některé sýkorky odletí, bude jich na větvi méně, nebo více?</p>`;choices(['Méně než na začátku.','Více než na začátku.'],i=>i===0?advance():message('Podívej se na sýkorky, které odletěly. Na větvi po nich zůstalo volné místo.',true))}else if(!task.valid.includes(route)){work.innerHTML=`<p>${esc(task.paths[route])}</p><label for="trial">Zkus si tuto cestu dopočítat. Co ti vyšlo?</label><input id="trial" class="number" inputmode="decimal"><div id="trial-result"></div>`;action('Porovnat s příběhem',()=>{const raw=document.getElementById('trial').value.trim();if(!raw){message('Napiš nejdřív svůj pokusný výsledek. Můžeš se také rovnou vrátit.',true);return}document.getElementById('trial-result').innerHTML=`<div class="note"><b>Tvůj pokus: ${esc(raw)}</b><p>${esc(task.explain[route])}</p></div>`;tone(false)});action('Vybral jsem jinou cestu. Zpět na rozcestí.',back)}else{work.innerHTML=`<p>${esc(task.explain[route])}</p>`;routeTool();action('Zpět na rozcestí',back)}}
if(stage===4){title('Výpočet je bonus navíc.');work.innerHTML=`<p class="instruction">${(!isCity(w)&&w===0)?'Příběh jsi ukázal správně. Chceš ještě spočítat sýkorky, které zůstaly?':'Rozumíš situaci a sestavil jsi správný postup. Můžeš ho teď dopočítat.'}</p><label for="answer">${(!isCity(w)&&w===0)?'Kolik sýkorek zůstalo?':(task.unit?`Výsledek (${esc(task.unit)})`:'Výsledek')}</label><input id="answer" class="number" inputmode="decimal" value="${esc(answerDraft)}"><p class="small-note">Pokračovat můžeš i bez výpočtu.</p>`;action('Zkontrolovat výsledek',()=>{const raw=document.getElementById('answer').value.trim(),n=Number(raw.replace(',','.'));answerDraft=raw;if(raw&&Number.isFinite(n)&&Math.abs(n-task.answer)<.0001){bonus=true;advance();}else message('Příběhu rozumíš a postup máš správný. Ve výpočtu ještě něco nesedí. Zkus ho opravit, nebo pokračuj bez bonusu.',true)},true);action('Pokračovat bez výpočtu',advance);document.getElementById('answer').onkeydown=e=>{if(e.key==='Enter')document.querySelector('#actions button').click()}}
if(stage===5){title((!isCity(w)&&w===0)?'Sýkorky ti děkují.':'Je to možné i ve skutečnosti?');if(!isCity(w)&&w===0){complete();return}choices([task.badcheck,task.check],i=>{if(i===1)complete();else message('Jak by tato kontrola odhalila chybu? Vyber kontrolu, která opravdu odpovídá příběhu.',true)})}
if(stage===6){
 if(isCity(w)){const world=cityWorld(w),district=world.districts[meta.topicId],reward=district.rewards[meta.topicOrder-1],topicCount=world.topicCount(meta.topicId,cityProgress[w]),next=world.nextUndone(meta.topicId,meta.id,cityProgress[w],cityModel(w).tasks);title(celebrate?`Nový prvek právě ožil: ${reward}.`:'Tuto proměnu už máš uloženou.');work.innerHTML=`<p class="instruction">Porozuměl jsi otázce, vybral jsi postup a ověřil jeho význam.</p><div class="city-reward" style="--accent:${district.accent}"><span>${meta.topicOrder}</span><div><b>${celebrate?`Nový prvek: ${reward}`:`${reward} už ve městě stojí`}</b><small>${district.name} · ${topicCount}/10</small></div></div><p>${celebrate?'Proměna se uložila do tohoto zařízení.':'Opakování ti odměnu nepřidalo podruhé a uložený pokrok zůstal beze změny.'} ${bonus?'Výpočet navíc byl také správný.':''}</p><p class="small-note">${topicCount===10?'Celý matematický okruh je dokončený — čtvrť se výrazně rozsvítila a dala do pohybu.':'Můžeš pokračovat další úlohou tohoto okruhu, nebo se vrátit do města a vybrat si cokoli jiného.'}</p>`;if(next){const b=action(`Přejít na další úlohu →`,()=>enter(w,next.id),true);b.id='next-task'}else{const b=action('Okruh je hotový — zpět do města →',()=>cityOverview(w),true);b.id='next-task'}action('Prohlédnout herní svět',()=>cityOverview(w));action('Zopakovat tuto úlohu',()=>enter(w,meta.id));document.onkeydown=null
 }else{title('Další kousek světa je tvůj.');work.innerHTML=`<p class="instruction">${w===0?'Ukázal jsi, co se stalo se sýkorkami, a spojil jsi příběh se správným zápisem.':'Porozuměl jsi otázce, vybral jsi postup a ověřil jeho význam.'}</p><div class="reward"><span class="sprite plank"></span><span class="sprite plank"></span><span class="sprite plank"></span></div><p>${celebrate?'Tři prkénka přibyla ke krmítku.':'Tento úkol už máš splněný. Krmítko na tebe čeká v dalším novém příběhu.'} ${bonus?'Získáváš také bonus za správný výpočet.':''}</p><p class="small-note">${done(w).length===10?'Prvních deset úkolů je hotovo. První část světa se vybarvila.':'Po deseti různých úkolech se vybarví první část světa.'}</p>`;const next=nextMission();if(next!==null){const b=action('Další úloha →',()=>enter(w,next),true);b.id='next-task';b.focus?.({preventScroll:true});document.onkeydown=e=>{if(stage===6&&e.key==='Enter'&&!e.repeat&&!['BUTTON','INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName)){e.preventDefault();enter(w,next)}}}else{const b=action('Vybrat další svět →',map,true);b.id='next-task';work.innerHTML+='<p class="note">Všech deset dostupných úloh tohoto světa máš hotových. Další úlohy teprve přibudou. Teď můžeš navštívit jiný svět.</p>';document.onkeydown=null}action('Zpět na mapu',map);action('Zkusit tento příběh znovu',()=>enter(w,mission))}
}
if(stage>0&&stage<6){const b=action('← Zpět k předchozímu kroku',previousStep);b.classList.add('back-step');document.getElementById('actions').prepend(b)}
}
function complete(){if(isCity(w)){const meta=cityTask(w);if(meta&&!cityDone(w,meta)){cityProgress[w]=[...cityProgress[w],meta.id];if(meta.missionIndex!==null&&!done(w).includes(meta.missionIndex))progress[w]=[...done(w),meta.missionIndex];persist();celebrate=true}else celebrate=false}else if(!done(w).includes(mission)){progress[w]=[...done(w),mission];persist();celebrate=true}else celebrate=false;stage=6;render();if(celebrate)tone(true,bonus)}
function birdBoard(){const task=t(),work=document.getElementById('work');work.innerHTML=`<p class="instruction">Do lesa odletí ${birdCount(task.away)}. Sýkorku přetáhneš z větve do lesa. Můžeš na ni také klepnout.</p><div class="bird-habitat" id="branch-zone"><span class="zone-label">NA VĚTVI</span><div class="birds" id="branch"></div></div><div class="bird-habitat forest-zone" id="forest-zone"><span class="zone-label">V LESE</span><div class="birds" id="forest"></div></div><p class="small-note">Sýkorku vrátíš klepnutím na ni v lese.</p>`;
for(let i=0;i<task.base;i++){const b=document.createElement('button');b.className='bird-token';b.innerHTML='<span class="sprite bird"></span>';b.setAttribute('aria-label',`${moved.has(i)?'Vrátit':'Nechat odletět'} sýkorku ${i+1}`);b.draggable=true;b.ondragstart=e=>e.dataTransfer.setData('text/plain',String(i));b.onclick=()=>{if(moved.has(i))moved.delete(i);else moved.add(i);render()};document.getElementById(moved.has(i)?'forest':'branch').append(b)}
for(const dest of ['branch','forest']){const el=document.getElementById(dest+'-zone');el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();const raw=e.dataTransfer.getData('text/plain'),i=Number(raw);if(raw!==''&&Number.isInteger(i)&&i>=0&&i<task.base){if(dest==='forest')moved.add(i);else moved.delete(i);render()}}}
action('Takto se to stalo',()=>{if(moved.size===task.away){advance();}else message(moved.size>task.away?`V lese je teď více sýkorek, než říká příběh. Některé vrať na větev.`:`V příběhu do lesa odletí ${birdCount(task.away)}. Zkus příběh ještě dokončit.`,true)},true)}
function groupBoard(){const target=t().k,work=document.getElementById('work');work.innerHTML=`<p class="instruction">${w===1?`Připrav pro každé dítě ${target} rohlíky. Tlačítkem přidáš jeden rohlík na jeho talíř.`:`Na každý záhon přidej sazenice rajčat. Na každém jich má být ${target}. Tlačítkem přidáš jednu sazenici.`}</p><div class="group-grid">${groups.map((n,i)=>`<div class="group"><b>${w===1?['Anička','Tomáš','Ema','Petr','Klára','Adam'][i]:`Záhon ${i+1}`}</b><div class="group-items">${Array.from({length:n},()=>`<span class="object ${w===1?'roll':'seedling'}" role="img" aria-label="${w===1?'rohlík':'sazenice rajčete'}"></span>`).join('')}</div><div class="group-buttons"><button data-minus="${i}" aria-label="Odebrat jednu položku ze skupiny ${i+1}">−</button><span>${n}</span><button data-plus="${i}" aria-label="Přidat jednu položku do skupiny ${i+1}">+</button></div></div>`).join('')}</div>`;work.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{groups[+b.dataset.plus]=Math.min(8,groups[+b.dataset.plus]+1);render()});work.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{groups[+b.dataset.minus]=Math.max(0,groups[+b.dataset.minus]-1);render()});action('Příběh je připravený',()=>{if(groups.every(n=>n===target)){advance();}else message(w===1?`Podívej se na každý talíř zvlášť. Má každé dítě právě ${target} rohlíky?`:`Podívej se na každý záhon zvlášť. Odpovídá počet sazenic na každém záhonu číslu ${target}?`,true)},true)}
function routeTool(){const task=t(),work=document.getElementById('work');
if(isCity(w)&&task.practice){work.innerHTML+=`<div class="percentage-tool"><b>Kontrola zvoleného postupu</b><p>${esc(task.practice.q)}</p></div>`;choices(task.practice.a,i=>i===task.practice.ok?advance():message('Tento zápis neodpovídá významu údajů v příběhu. Vrať se k zadání a zkus si říct, co jednotlivá čísla znamenají.',true));return}
if(w===8){work.innerHTML+=`<div class="tariff-tool"><label for="minutes">Vyzkoušej počet minut</label><input id="minutes" type="range" min="0" max="100" step="10" value="${modelValue||0}"><div id="tariff-values"></div></div><p>Co znamená hledaný bod, kde se ceny setkají?</p>`;const update=()=>{const n=+document.getElementById('minutes').value;modelValue=String(n);document.getElementById('tariff-values').innerHTML=`<strong>${n} minut</strong><div class="price-row"><b>A</b><div class="price-bar" style="width:${90*(task.feeA+task.rateA*n)/Math.max(task.feeA+task.rateA*100,task.feeB+task.rateB*100)}%">${task.feeA+task.rateA*n} Kč</div></div><div class="price-row"><b>B</b><div class="price-bar b" style="width:${90*(task.feeB+task.rateB*n)/Math.max(task.feeA+task.rateA*100,task.feeB+task.rateB*100)}%">${task.feeB+task.rateB*n} Kč</div></div>`};document.getElementById('minutes').oninput=update;update();choices(['Stejný počet minut vede u obou nabídek ke stejné celkové ceně.','Obě nabídky mají stejný měsíční poplatek.'],i=>i===0?advance():message('Měsíční poplatky se nemění. Hledáme shodu celkových cen za stejný počet minut.',true));return}
const prompts={1:['Který zápis odpovídá tvým talířům?',route===0?[`${task.n} × ${task.k}`,`${task.n} + ${task.k}`]:[Array(task.n).fill(task.k).join(' + '),`${task.n} + ${task.k}`],0],2:['Který zápis odpovídá tvým záhonům?',route===0?[`${task.n} × ${task.k}`,`${task.n} + ${task.k}`]:[Array(task.n).fill(task.k).join(' + '),`${task.n} + ${task.k}`],0],3:['Které jednotky bude mít výsledek?', ['metry čtvereční — měříme plochu.','metry — měříme délku plotu.'],1],4:['Čím vydělíš objem vody, abys získal výšku?', ['Obsahem dna.','Obvodem dna.'],0],5:[`Po vynásobení ${task.n} × ${task.scale} získáš…`,['délku ve skutečnosti v centimetrech.','délku ve skutečnosti v kilometrech.'],0],6:[`Úsporu ${task.loss} kWh porovnáváš s…`,[`${task.base} kWh, protože to byla původní spotřeba.`,`${task.left} kWh, protože to je nová spotřeba.`],0],7:['Kterou stranu trojúhelníku představuje žebřík?',['Nejdelší stranu proti pravému úhlu.','Vodorovnou stranu podél země.'],0]};
if(w===4){work.innerHTML+=`<div class="water-tool"><label for="litres">Prozkoumej: kolik vody nalijeme?</label><input id="litres" type="range" min="0" max="200" step="5" value="${modelValue||0}"><div class="water-tank"><div id="water-fill"></div><span id="water-label"></span></div><small>Dno: 100 × 40 cm · výška nádrže: 50 cm</small></div>`;const update=()=>{const v=+document.getElementById('litres').value;modelValue=String(v);document.getElementById('water-fill').style.height=v/2+'%';document.getElementById('water-label').textContent=`${v} litrů · hladina ${(v/4).toLocaleString('cs-CZ')} cm`};document.getElementById('litres').oninput=update;update()}
const [q,a,ok]=prompts[w];const p=document.createElement('p');p.textContent=q;work.append(p);choices(a,i=>i===ok?advance():message('Vrať se k významu veličin v příběhu. '+(w===4?'Voda pokrývá celé dno, ne jen jeho okraj.':'Zkus si zvolený údaj nebo zápis vysvětlit vlastními slovy.'),true))}
function showHint(){hint++;const task=t();let text;if(!isCity(w)&&w===0){text=stage<=1?(hint===1?'Poslechni si příběh ještě jednou. Které sýkorky zůstaly a které odletěly?':`Do lesa patří ${birdCount(task.away)}. Ostatní mají zůstat na větvi.`):'Když sýkorky odletěly, ptáků na větvi ubylo. Ubrání zapisujeme znaménkem minus.'}else if(stage<=1){text=isCity(w)?(hint===1?'Řekni vlastními slovy, co máme zjistit. Které údaje k tomu potřebuješ?':task.model):w===1?`Začni u Aničky. Připrav pro ni ${task.k} rohlíky. Potom připrav stejnou svačinu pro ostatní děti.`:w===2?`Začni jedním záhonem. Počet sazenic na něm má být ${task.k}. Potom připrav stejně i ostatní záhony.`:hint===1?'Řekni vlastními slovy, co máme zjistit. Které údaje k tomu potřebuješ?':task.model}else text=hint===1?'Zkus si vybranou cestu nakreslit nebo ji popsat nahlas. Můžeš se vrátit na rozcestí.':`Použít můžeš obě tyto cesty: ${task.paths[0]} Nebo: ${task.paths[1]}`;document.getElementById('help').innerHTML=`<aside class="note">${esc(text)}</aside>`;}
function openFromLink(search=window.location?.search||''){
 const params=new URLSearchParams(search),grade=params.get('rocnik'),task=params.get('uloha');
 if(/^[1-9]$/.test(grade||'')&&/^(?:[1-9]|10)$/.test(task||''))enter(Number(grade)-1,Number(task)-1);else map();
}
document.getElementById('home').onclick=map;document.getElementById('sound').onclick=()=>{sound=!sound;const b=document.getElementById('sound');b.textContent=sound?'♫ Zvuk zapnutý':'♫ Zvuk vypnutý';b.setAttribute('aria-pressed',String(sound))};openFromLink();
