'use strict';
const worlds=[['Ptačí háj','🌳','🐦'],['Tržní přístav','⛵','🍎'],['Údolí dílen','🏡','🌾'],['Město mostů','🌉','🚋'],['Jezerní laboratoř','🏞️','🐟'],['Horská železnice','🏔️','🚂'],['Energetické město','🏙️','💡'],['Inženýrská stanice','🔭','🛰️'],['Rada budoucnosti','🏛️','🌍']];
const tasks=[
{story:'Na větvi sedí 6 sýkorek. Dvě odletí do lesa.',question:'Kolik sýkorek zůstane na větvi?',other:'Kolik sýkorek přiletělo?',paths:['Odeberu dvě ze šesti.','Dopočítám od dvou do šesti.','Přidám dvě k šesti.'],valid:[0,1],explain:['Šest ptáků, dva pryč. Počítáš zbývající ptáky.','Hledáš, kolik chybí od dvou odletělých do původních šesti.','Přidáním bys měl osm ptáků. V příběhu ale ptáci odletěli.'],answer:4,unit:'sýkorky',check:'Po odletu musí být na větvi méně než šest ptáků.',badcheck:'Po odletu musí být ptáků více.',model:'Šest celkem = dva odletělí + zbývající.'},
{story:'Čtyři děti dostanou každé tři rohlíky.',question:'Kolik rohlíků potřebujeme pro všechny děti?',other:'Kolik rohlíků dostane jedno dítě?',paths:['Sestavím čtyři skupiny po třech.','Sečtu 3 + 3 + 3 + 3.','Sečtu počet dětí a rohlíků: 4 + 3.'],valid:[0,1],explain:['Čtyři stejně velké skupiny vyjádříš jako 4 × 3.','Každému dítěti patří jedna trojka.','Sedm nezahrnuje tři rohlíky pro každé dítě. Zkus rozdělení ukázat.'],answer:12,unit:'rohlíků',check:'Výsledek musí stačit na čtyři trojice.',badcheck:'Stačí, když je rohlíků víc než tři.',model:'Dítě 1: 🥐🥐🥐 | Dítě 2: 🥐🥐🥐 | Dítě 3: 🥐🥐🥐 | Dítě 4: 🥐🥐🥐'},
{story:'Na šesti záhonech rostou po čtyřech sazenicích.',question:'Kolik sazenic roste celkem?',other:'Kolik sazenic je na jednom záhonu?',paths:['Vynásobím 6 × 4.','Spočtu tři záhony a výsledek zdvojnásobím.','Vydělím 6 : 4.'],valid:[0,1],explain:['Šest řad, každá má čtyři sazenice.','Dvě poloviny po třech záhonech dají celý počet.','Dělení zde nepočítá všechny sazenice v šesti skupinách.'],answer:24,unit:'sazenic',check:'Celek musí být větší než čtyři a dělitelný šesti.',badcheck:'Celek musí být menší než šest.',model:'🌱🌱🌱🌱 × šest záhonů'},
{story:'Zahrada má rozměry 8 × 5 metrů. V plotě bude dvoumetrová branka.',question:'Kolik metrů plotu je potřeba bez branky?',other:'Jaký obsah má zahrada?',paths:['Sečtu všechny čtyři strany a odečtu branku.','Spočtu 2 × (8 + 5) − 2.','Spočtu 8 × 5 − 2.'],valid:[0,1],explain:['Plot vede po hranici, branka nahrazuje dva metry plotu.','Dva páry stejně dlouhých stran tvoří obvod.','Násobení 8 × 5 měří plochu, nikoli délku hranice.'],answer:24,unit:'m',check:'Délka plotu je o dva metry menší než obvod.',badcheck:'Délka plotu musí odpovídat obsahu v m².',model:'Hranice: 8 m + 5 m + 8 m + 5 m. Branka: 2 m.'},
{story:'Akvárium má vnitřní délku 100 cm, šířku 40 cm a výšku 50 cm. Obsahuje 65 litrů vody; uvnitř nejsou dekorace.',question:'Jak vysoko sahá voda?',other:'Jaký je obvod dna?',paths:['Převedu litry na cm³ a objem vydělím obsahem dna.','Převedu dno na 10 × 4 dm a počítám v litrech = dm³.','Vydělím 65 součtem 100 + 40.'],valid:[0,1],explain:['65 000 cm³ ÷ 4 000 cm² dává výšku v cm.','65 dm³ ÷ 40 dm² dává výšku v dm. Tu převedeš na cm.','Součet stran není plocha dna. Vrstva vody vyplňuje celé dno.'],answer:16.25,unit:'cm',check:'Vrstva vysoká 1 cm pojme 4 litry, takže 65 litrů sahá mezi 16 a 17 cm.',badcheck:'65 litrů vždy znamená hladinu 65 cm.',model:'Dno = 100 × 40 = 4 000 cm². Jeden centimetr výšky = 4 litry.'},
{story:'Na mapě v měřítku 1 : 25 000 měří trať 8 cm.',question:'Jaká je skutečná délka tratě v kilometrech?',other:'Kolik centimetrů měří trať na mapě?',paths:['Vynásobím 8 × 25 000 a převedu cm na km.','Zjistím délku pro 1 cm a pak ji osminásobím.','Vydělím 8 číslem 25 000.'],valid:[0,1],explain:['Každý centimetr mapy odpovídá 25 000 cm skutečnosti.','1 cm mapy znamená 250 m, osm centimetrů osmkrát tolik.','Skutečná trať je větší než její obraz na mapě, ne menší.'],answer:2,unit:'km',check:'Osm úseků po 250 metrech dává délku v řádu kilometrů.',badcheck:'Skutečná trať musí být kratší než 8 cm.',model:'1 cm → 250 m; 8 cm → osmkrát delší úsek.'},
{story:'Město snížilo denní spotřebu energie z 800 na 680 jednotek.',question:'O kolik procent původní spotřeby klesla spotřeba?',other:'Kolik procent nové spotřeby tvoří úbytek?',paths:['Úbytek vydělím původní spotřebou a násobím stem.','Spočtu, kolik procent původní spotřeby zbylo, a odečtu od 100 %.','Úbytek vydělím novou spotřebou a násobím stem.'],valid:[0,1],explain:['Základ je původních 800 jednotek.','680 je zbývající část původního celku.','Tato cesta používá jiný základ. Odpovídala by otázce na podíl z nové spotřeby.'],answer:15,unit:'%',check:'Deset procent je 80 jednotek; úbytek 120 je větší než 10 %, ale menší než 20 %.',badcheck:'Úbytek 120 jednotek automaticky znamená 120 %.',model:'Původní celek: 800. Zbývá: 680. Úbytek: 120.'},
{story:'Plošina je 4 m vysoko. Pata žebříku bude 3 m od kolmé stěny.',question:'Jak dlouhý žebřík dosáhne přesně k plošině?',other:'Jaký je součet vzdálenosti od stěny a výšky?',paths:['Použiju pravoúhlý trojúhelník: odmocnina z (4² + 3²).','Poznám pravoúhlý trojúhelník s poměrem stran 3 : 4 : 5.','Sečtu 4 + 3.'],valid:[0,1],explain:['Žebřík je přepona, ne jedna z odvěsen.','Známou trojici je možné ověřit: 3² + 4² = 5².','Součet vede podél země a potom vzhůru, ne přímo po žebříku.'],answer:5,unit:'m',check:'Žebřík musí být delší než 4 m, ale kratší než cesta 3 + 4 m.',badcheck:'Žebřík musí být kratší než výška plošiny.',model:'Odvěsny: 3 m a 4 m. Přepona: hledaná délka žebříku.'},
{story:'Tarif A stojí 100 Kč měsíčně + 4 Kč za minutu. Tarif B stojí 200 Kč měsíčně + 2 Kč za minutu.',question:'Při kolika minutách stojí oba tarify stejně?',other:'Který tarif je vždy levnější bez ohledu na volání?',paths:['Sestavím rovnici 100 + 4x = 200 + 2x.','Rozdíl paušálů vydělím rozdílem minutových cen.','Porovnám jen paušály: A je vždy levnější.'],valid:[0,1],explain:['Hledáš takové x, pro které jsou obě celkové ceny stejné.','B stojí na začátku o 100 Kč víc, každou minutou ale ušetří 2 Kč.','Levnější paušál nemusí znamenat levnější celkovou cenu. Zkus dosadit 100 minut.'],answer:50,unit:'minut',check:'Dosadím stejný počet minut do obou cen a porovnám částky.',badcheck:'Stačí porovnat měsíční paušály.',model:'A: 100 + 4 × minuty. B: 200 + 2 × minuty.'}
];
const key='fajn-rozumim-v1';let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch{}let completed=Array.isArray(saved.completed)?saved.completed.filter(n=>Number.isInteger(n)&&n>=0&&n<9):[];let sound=true,w=0,phase=0,route=null,moved=0,hint=0,bonus=false;
const app=document.getElementById('app');const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tone(ok){if(!sound)return;try{const c=new AudioContext();[...(ok?[523,659,784]:[220,175])].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+i*.12;o.frequency.value=f;g.gain.setValueAtTime(.08,t);g.gain.exponentialRampToValueAtTime(.001,t+.2);o.connect(g).connect(c.destination);o.start(t);o.stop(t+.22)});setTimeout(()=>c.close(),800)}catch{}}
function feedback(text,bad=false){const e=document.getElementById('feedback');if(e){e.textContent=text;e.className='feedback'+(bad?' bad':'')}tone(!bad)}
function persist(){try{localStorage.setItem(key,JSON.stringify({completed}))}catch{}}
function map(){app.innerHTML=`<div class="intro"><p>DEVĚT SVĚTŮ POROZUMĚNÍ · PRVNÍ HRATELNÁ VERZE</p><h1>Kde dnes začne tvoje cesta?</h1><p>Vyber kterýkoli ročník. Vstup nic neobarví — svět ožívá až za splněné mise.</p></div><div class="grid">${worlds.map((x,i)=>`<button class="world ${completed.includes(i)?'done':''}" data-world="${i}"><div class="art">${x[1]} ${x[2]}</div><div class="copy"><span class="tag">${i+1}. ročník</span><h2>${x[0]}</h2><p>${completed.includes(i)?'Úvodní sektor splněn · další sektory se připravují':'Nesplněno · vstup volný'}</p></div></button>`).join('')}</div><footer>V této verzi je jedna úvodní mise pro každý ročník. Celé světy se 100 misemi zatím hotové nejsou. Pokrok se ukládá pouze v tomto prohlížeči.</footer>`;app.querySelectorAll('[data-world]').forEach(b=>b.onclick=()=>enter(+b.dataset.world))}
function enter(i){w=i;phase=0;route=null;moved=0;hint=0;bonus=false;render()}
function buttons(labels,fn){const d=document.createElement('div');d.className='choices';labels.forEach((s,i)=>{const b=document.createElement('button');b.textContent=s;b.onclick=()=>fn(i);d.append(b)});document.getElementById('work').append(d)}
function render(){const t=tasks[w],done=completed.includes(w);app.innerHTML=`<div class="steps">${w+1}. ročník · ${worlds[w][0]} · Úvodní mise</div><div class="workspace"><section><div class="land ${done?'alive':''}"><span>${worlds[w][1]}</span><span class="character">${worlds[w][2]}</span><span class="caption">${done?'Úvodní sektor ožil':'Nesplněný sektor zůstává šedý'}</span></div><div class="card" style="margin-top:18px"><h2>${esc(t.story)}</h2><p><strong>${esc(t.question)}</strong></p><div class="toolbar"><button class="action" id="read">♫ Přečíst</button><button class="action" id="hint">☀ Nápověda</button></div><div id="hintbox"></div><div class="supply">${done?'🪵 🪵 🪵 → 🏡':'Staveniště čeká na první materiál.'}</div><p>Odměnu získáš za porozumění, model a postup. Výpočet je dobrovolný bonus.</p></div></section><section class="card"><div class="meters"><span>${phase>0?'✓':'○'} Rozumím</span><span>${phase>2?'✓':'○'} Postup a model</span><span>${bonus?'★':'○'} Výpočet</span></div><h2 style="margin-top:24px" id="title"></h2><div id="work"></div><div id="feedback" class="feedback" aria-live="polite">Zkoušení i návrat jsou součást řešení.</div></section></div>`;
document.getElementById('read').onclick=()=>{if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t.story+' '+t.question);u.lang='cs-CZ';speechSynthesis.speak(u)}};
document.getElementById('hint').onclick=()=>{hint++;document.getElementById('hintbox').innerHTML=`<div class="note">${esc(hint===1?'Co známe a co máme zjistit? Zkus si příběh převyprávět.':hint===2?t.model:'Můžeš zvolit obě první cesty: '+t.paths[0]+' Nebo: '+t.paths[1])}</div>`};
const title=s=>document.getElementById('title').textContent=s;
if(phase===0){title('Co máme zjistit?');buttons([t.other,t.question],i=>{if(i===1){phase=1;render();tone(true)}else feedback('To je jiná otázka. Porovnej ji s otázkou v zadání.',true)})}
if(phase===1){title('Vyber cestu, kterou chceš vyzkoušet');buttons(t.paths,i=>{route=i;phase=2;render()})}
if(phase===2){title('Vyzkoušej svůj model');const work=document.getElementById('work');work.innerHTML=`<p>${esc(t.explain[route])}</p><div class="note">${esc(t.model)}</div>`;
if(!t.valid.includes(route)){const input=document.createElement('input');input.className='number';input.placeholder='Co by touto cestou vyšlo?';input.setAttribute('aria-label','Pokusný výsledek slepé cesty');work.append(input);buttons(['Vyzkoušet a porovnat se zadáním','Vrátit se na rozcestí'],i=>{if(i===0)feedback(t.explain[route]+' Můžeš se vrátit a změnit postup.',true);else{phase=1;render()}})}
else if(w===0){work.innerHTML+=`<p>Přesuň dvě sýkorky do lesa. Lze přetáhnout nebo kliknout. Přesunutou sýkorku můžeš vrátit kliknutím.</p><div class="zone"><b>Na větvi</b><div class="tokens" id="branch"></div></div><div class="zone" id="forest"><b>Les</b><div class="tokens" id="gone"></div></div><div class="math">6 − ${moved} = ${6-moved}</div>`;for(let i=0;i<6;i++){const b=document.createElement('button');b.className='token';b.textContent='🐦';b.setAttribute('aria-label',i<moved?'Vrátit sýkorku':'Přesunout sýkorku');b.onclick=()=>{moved+=i<moved?-1:1;render()};b.draggable=i>=moved;b.ondragstart=e=>e.dataTransfer.setData('text/plain','bird');document.getElementById(i<moved?'gone':'branch').append(b)}const forest=document.getElementById('forest');forest.ondragover=e=>e.preventDefault();forest.ondrop=e=>{e.preventDefault();if(e.dataTransfer.getData('text/plain')==='bird'&&moved<6){moved++;render()}};buttons(['Model je připraven','Zpět na rozcestí'],i=>{if(i===1){phase=1;render()}else if(moved===2){phase=3;render();tone(true)}else feedback('Porovnej počet odletělých s příběhem. Můžeš ptáky vrátit.',true)})}
else{if(w===4)work.innerHTML+='<div class="water"><span>100 × 40 cm · 65 litrů · nádrž vysoká 50 cm</span></div>';buttons(['Model odpovídá otázce — pokračovat','Zpět na rozcestí'],i=>{phase=i===0?3:1;render()})}}
if(phase===3){title('Chceš dopočítat bonus?');document.getElementById('work').innerHTML=`<label for="answer">Výsledek v jednotce: ${esc(t.unit)}</label><input id="answer" class="number" inputmode="decimal" autocomplete="off">`;buttons(['Ověřit výpočet','Pokračovat bez výpočtu'],i=>{if(i===1){phase=4;render()}else{const raw=document.getElementById('answer').value.trim();const n=Number(raw.replace(',','.'));if(raw&&Number.isFinite(n)&&Math.abs(n-t.answer)<.00001){bonus=true;phase=4;render();tone(true)}else feedback('Postup máš správně. Početní výsledek zatím nesedí — můžeš ho opravit nebo pokračovat bez bonusu.',true)}});document.getElementById('answer').onkeydown=e=>{if(e.key==='Enter')document.querySelector('#work .choices button').click()}}
if(phase===4){title('Jak ověříš, že je výsledek reálný?');buttons([t.check,t.badcheck],i=>{if(i===0){if(!completed.includes(w))completed.push(w);persist();phase=5;render();tone(true)}else feedback('Tahle kontrola neověřuje vztahy z příběhu. Zkus druhou možnost.',true)})}
if(phase===5){title('Úvodní sektor ožil!');document.getElementById('work').innerHTML=`<p>Rozumíš otázce a zvolil jsi použitelný postup. Tři kusy dřeva vytvořily první domek.</p><div class="supply">🪵 🪵 🪵 → 🏡 ${bonus?'🌻':''}</div><p>${bonus?'Slunečnice je bonus za správný výpočet.':'Misi jsi splnil i bez početního bonusu.'}</p>`;buttons(['Zpět na mapu','Vyzkoušet jinou cestu'],i=>i===0?map():enter(w))}
}
document.getElementById('home').onclick=map;document.getElementById('sound').onclick=()=>{sound=!sound;document.getElementById('sound').textContent=sound?'♫ Zvuk zapnutý':'♫ Zvuk vypnutý';document.getElementById('sound').setAttribute('aria-pressed',String(sound))};map();
