'use strict';
(function(){
const defs=[
['velkaCisla','Velká čísla'],['scitani','Sčítání a odčítání'],['nasobeni','Násobení a dělení'],['poradi','Pořadí operací'],['zlomky','Části celku a zlomky'],['desetinna','Desetinná čísla'],['jednotky','Jednotky a převody'],['obvodObsah','Obvod a obsah'],['penize','Peníze a nákupy'],['vicekrokove','Vícekrokové úlohy']];
const topics=defs.map(function(x){return{id:x[0],name:x[1],rewardId:'district-'+x[0]};});
function mk(title,story,question,other,paths,explain,answer,unit,check,badcheck,model,practice){var mc=practice||{q:'Co v příběhu znamenají uvedené údaje?',a:['Popisují množství a vztahy, které potřebujeme k řešení.','Jsou to jen čísla bez významu.'],ok:0};var pr={q:'Který postup odpovídá příběhu?',a:[paths[0],paths[2]||paths[1]],ok:0};return{title:title,story:story,question:question,other:other,paths:paths,valid:[0,1],explain:explain,answer:answer,unit:unit,check:check,badcheck:badcheck,model:model,modelChoice:mc,practice:pr};}
const tasks=[];
function add(topic,i,data){var meta=topics.find(function(t){return t.id===topic;});var task=Object.assign({},data);task.id='g5-'+topic+'-'+String(i+1).padStart(2,'0');task.grade=5;task.topicId=topic;task.topic=meta?meta.name:topic;task.topicOrder=i+1;task.difficulty=i<3?'lehká':i<7?'střední':'výzva';task.rewardId='district-'+topic;task.available=true;task.missionIndex=null;task.content=data;tasks.push(task);}
const pairs=[[12540,3200],[24800,4600],[31500,7500],[42750,5250],[53600,6400],[64200,5800],[70500,9500],[81600,8400],[90400,9600],[120000,15000]];
pairs.forEach(function(v,i){var a=v[0],b=v[1],plus=i%2===0,ans=plus?a+b:a-b,op=plus?'+':'−';add('velkaCisla',i,mk('Velká čísla '+(i+1),['Na začátku máme '+a+' bodů.',plus?'Přibylo dalších '+b+' bodů.':'Ubylo '+b+' bodů.'],plus?'Kolik bodů máme nyní?':'Kolik bodů zůstalo?','O kolik bodů se počet změnil?',[a+' '+op+' '+b+'.',plus?'Přidám nové body k původním.':'Od původního počtu odečtu úbytek.',a+' '+(plus?'−':'+')+' '+b+'.'],[a+' '+op+' '+b+' = '+ans+'.',plus?'Počet se zvětšil.':'Počet se zmenšil.','Tento zápis vypráví opačný příběh.'],ans,'bodů',plus?'Výsledek musí být větší než původní počet.':'Výsledek musí být menší než původní počet.','Výsledek jde opačným směrem než děj.','Nejdřív rozhodni, zda množství přibylo, nebo ubylo.',{q:'Co se s počtem stalo?',a:[plus?'Zvětšil se.':'Zmenšil se.',plus?'Zmenšil se.':'Zvětšil se.'],ok:0}));});
const ab=[[3850,1275],[6200,2380],[7450,1850],[9300,4650],[5680,2320],[8100,3750],[4600,2950],[10000,6840],[7250,1750],[9990,3210]];
ab.forEach(function(v,i){var a=v[0],b=v[1],plus=i%3===0,ans=plus?a+b:a-b,op=plus?'+':'−';add('scitani',i,mk('Školní sbírka '+(i+1),['Ve sbírce bylo '+a+' kusů.',plus?'Přinesli dalších '+b+' kusů.':'Použilo se '+b+' kusů.'],plus?'Kolik kusů je nyní ve sbírce?':'Kolik kusů zůstalo?','Kolik bylo na začátku?',[a+' '+op+' '+b+'.',plus?'Spojím oba počty.':'Od začátku odeberu použité kusy.',a+' '+(plus?'−':'+')+' '+b+'.'],['Výsledek je '+ans+'.','Slovní změna určuje správnou operaci.','Tato operace by změnu obrátila.'],ans,'kusů','Výsledek musí odpovídat směru změny.','Na význam slov nemusíme brát ohled.','Ptej se, zda množství roste, nebo klesá.',{q:'Co je důležité?',a:['Co se s množstvím stalo.','Které číslo je delší.'],ok:0}));});
const groups=[[8,24],[6,35],[9,18],[7,42],[12,15],[5,64],[16,14],[25,8],[18,12],[20,17]];
groups.forEach(function(v,i){var n=v[0],k=v[1],divide=i%2===1,total=n*k,ans=divide?n:total;add('nasobeni',i,mk('Stejné skupiny '+(i+1),divide?['Máme '+total+' předmětů.','Do jedné skupiny patří '+k+' předmětů.']:['Máme '+n+' stejných skupin.','V každé je '+k+' předmětů.'],divide?'Kolik skupin vytvoříme?':'Kolik předmětů je dohromady?','Kolik je v jedné skupině?',divide?[total+' ÷ '+k+'.','Hledám počet stejných skupin.',total+' × '+k+'.']:[n+' × '+k+'.','Sečtu '+k+' celkem '+n+'krát.',n+' + '+k+'.'],divide?[total+' ÷ '+k+' = '+ans+'.','Kontrola násobením vrátí '+total+'.','Násobení by počet zvětšilo.']:[n+' × '+k+' = '+ans+'.','Stejné skupiny zapisujeme násobením.','Součet dvou údajů nestačí.'],ans,divide?'skupin':'kusů',divide?'Počet skupin krát velikost skupiny dá celek.':'Výsledek musí odpovídat všem skupinám.','Kontrola neodpovídá příběhu.',divide?'Dělením hledáme počet stejných skupin.':'Násobením spojujeme stejné skupiny.',{q:'Co hledáme?',a:[divide?'Počet skupin.':'Celkový počet.','Nesouvisející součet.'],ok:0}));});
const order=[[12,4,5],[20,3,6],[15,5,8],[30,4,7],[18,6,9],[25,5,4],[40,8,3],[16,4,12],[50,10,6],[24,6,11]];
order.forEach(function(v,i){var a=v[0],b=v[1],c=v[2],ans=a+b*c;add('poradi',i,mk('Nákup v balíčcích '+(i+1),['Jedna věc stojí '+a+' Kč.','Kupujeme ještě '+b+' balíčky po '+c+' Kč.'],'Kolik zaplatíme celkem?','Kolik stojí jen balíčky?',[a+' + '+b+' × '+c+'.','Nejdřív spočítám cenu balíčků, potom přidám samostatnou věc.','('+a+' + '+b+') × '+c+'.'],[b+' × '+c+' = '+(b*c)+'; potom + '+a+' = '+ans+' Kč.','Násobení spočítá stejné balíčky.','Závorka by znamenala jiný nákup.'],ans,'Kč','Cena balíčků plus samostatná věc musí dát celý nákup.','Sčítání se vždy počítá před násobením.','Násobení má přednost před sčítáním.',{q:'Co spočítáme jako první?',a:[b+' × '+c,a+' + '+b],ok:0}));});
const fr=[[20,1,2],[24,1,3],[28,1,4],[30,2,5],[36,3,4],[40,3,5],[48,5,6],[50,7,10],[60,2,3],[80,3,8]];
fr.forEach(function(v,i){var whole=v[0],n=v[1],d=v[2],ans=whole*n/d;add('zlomky',i,mk('Část celku '+(i+1),['Celkem je '+whole+' kusů.','Potřebujeme '+n+'/'+d+' tohoto množství.'],'Kolik kusů hledáme?','Kolik kusů je celý počet?',[whole+' ÷ '+d+' × '+n+'.','Nejdřív zjistím jednu část a pak vezmu '+n+' takových částí.',whole+' ÷ '+n+'.'],[whole+' ÷ '+d+' × '+n+' = '+ans+'.','Jmenovatel říká počet stejných částí.','Dělení čitatelem neodpovídá významu zlomku.'],ans,'kusů','Část celku nemůže být větší než celek.','Část musí být větší než celek.','Nejprve rozděl celek podle jmenovatele.',{q:'Co říká jmenovatel?',a:['Na kolik stejných částí je celek rozdělen.','Kolik celků máme.'],ok:0}));});
const dec=[[12.5,2.4],[8.75,1.25],[15.6,3.2],[20.5,7.75],[6.4,2.35],[30.25,10.5],[18.8,4.6],[9.9,3.45],[42.5,12.25],[50,16.75]];
dec.forEach(function(v,i){var a=v[0],b=v[1],plus=i%2===0,ans=Number((plus?a+b:a-b).toFixed(2)),op=plus?'+':'−';add('desetinna',i,mk('Měření '+(i+1),['První délka je '+a+' m.',plus?'Přidáme '+b+' m.':'Odebereme '+b+' m.'],plus?'Jaká je celková délka?':'Jaká délka zůstane?','Jaká byla druhá délka?',[a+' '+op+' '+b+'.','Při písemném počítání srovnám desetinné čárky.',a+' '+(plus?'−':'+')+' '+b+'.'],[a+' '+op+' '+b+' = '+ans+'.','Počítáme stejné řády se stejnými řády.','Tato operace obrací příběh.'],ans,'m','Výsledek musí odpovídat tomu, zda přidáváme, nebo ubíráme.','Desetinnou čárku můžeme libovolně posunout.','U desetinných čísel hlídáme řády.',{q:'Co zarovnáme při písemném výpočtu?',a:['Desetinné čárky.','Čísla zleva.'],ok:0}));});
const units=[[3,'km',3000,'m'],[5,'m',500,'cm'],[7,'kg',7000,'g'],[4,'l',4000,'ml'],[6,'h',360,'min'],[250,'cm',2.5,'m'],[3500,'g',3.5,'kg'],[180,'min',3,'h'],[2500,'ml',2.5,'l'],[4500,'m',4.5,'km']];
units.forEach(function(v,i){var a=v[0],u=v[1],ans=v[2],to=v[3];add('jednotky',i,mk('Převod jednotek '+(i+1),['Máme '+a+' '+u+'.','Potřebujeme stejné množství vyjádřit v '+to+'.'],'Kolik '+to+' to je?','Jaká byla původní hodnota?',['Použiji vztah mezi oběma jednotkami.','Převedu celé množství, ne jen značku jednotky.','Jen změním značku jednotky.'],['Po převodu dostaneme '+ans+' '+to+'.','Skutečné množství zůstává stejné.','Pouhá změna značky by změnila množství.'],ans,to,'Po převedení zpět dostaneme původní množství.','Stačí změnit značku jednotky.','Převod zachovává stejné skutečné množství.',{q:'Co se při převodu nemění?',a:['Skutečné množství.','Číselná hodnota.'],ok:0}));});
const rect=[[6,4],[8,5],[10,7],[12,6],[9,9],[15,8],[14,5],[20,7],[11,6],[16,10]];
rect.forEach(function(v,i){var a=v[0],b=v[1],per=i%2===0,ans=per?2*(a+b):a*b;add('obvodObsah',i,mk('Zahrada '+(i+1),['Zahrada měří '+a+' m na délku.','Na šířku má '+b+' m.'],per?'Kolik metrů plotu potřebujeme kolem zahrady?':'Kolik metrů čtverečních zabírá zahrada?','Jaké má zahrada rozměry?',per?['2 × ('+a+' + '+b+').','Sečtu délky všech čtyř stran.',a+' × '+b+'.']:[a+' × '+b+'.','Spočítám čtvercové metry uvnitř.','2 × ('+a+' + '+b+').'],per?['Obvod je '+ans+' m.','Plot vede kolem všech stran.','Součin stran počítá plochu.']:['Obsah je '+ans+' m².','Uvnitř je '+ans+' čtvercových metrů.','Tento výpočet počítá okraj.'],ans,per?'m':'m²',per?'Plot měříme v metrech.':'Plochu měříme ve čtverečních metrech.','Jednotka neodpovídá tomu, co měříme.',per?'Obvod je délka kolem útvaru.':'Obsah je plocha uvnitř útvaru.',{q:per?'Kde vede obvod?':'Co měří obsah?',a:[per?'Kolem zahrady.':'Plochu uvnitř.','Něco jiného.'],ok:0}));});
const buy=[[8,35],[6,45],[5,60],[4,75],[7,28],[9,32],[3,120],[12,25],[10,42],[8,55]];
buy.forEach(function(v,i){var n=v[0],price=v[1],ans=n*price;add('penize',i,mk('Nákup '+(i+1),['Kupujeme '+n+' stejných věcí.','Jedna stojí '+price+' Kč.'],'Kolik zaplatíme celkem?','Kolik stojí jedna věc?',[n+' × '+price+'.','Sečtu cenu '+price+' Kč celkem '+n+'krát.',n+' + '+price+'.'],[n+' × '+price+' = '+ans+' Kč.','Stejná cena se opakuje pro každý kus.','Součet počtu kusů a ceny nedává cenu nákupu.'],ans,'Kč','Celkovou cenu můžeme vydělit počtem kusů.','Počet kusů stačí přičíst k ceně.','Celková cena je počet kusů krát cena za kus.',{q:'Co znamená cena za kus?',a:['Stejnou částku za každý kus.','Cenu celého nákupu.'],ok:0}));});
const multi=[[4,6,15],[5,8,12],[3,9,20],[6,7,14],[8,5,18],[4,12,16],[7,6,22],[5,10,25],[9,4,30],[6,11,17]];
multi.forEach(function(v,i){var g=v[0],each=v[1],extra=v[2],ans=g*each+extra;add('vicekrokove',i,mk('Výprava na dva kroky '+(i+1),['Máme '+g+' skupin po '+each+' dětech.','Pak se přidá ještě '+extra+' dětí.'],'Kolik dětí je nakonec dohromady?','Kolik dětí bylo v původních skupinách?',[g+' × '+each+' + '+extra+'.','Nejdřív spočítám děti ve skupinách, potom přidám další.',g+' + '+each+' + '+extra+'.'],[g+' × '+each+' = '+(g*each)+'; potom + '+extra+' = '+ans+'.','Příběh má dva kroky.','Počet skupin nelze prostě přičíst k počtu dětí ve skupině.'],ans,'dětí','Konečný počet musí být větší než počet v původních skupinách.','Konečný počet má být menší.','Vícekrokovou úlohu rozložíme na smysluplné kroky.',{q:'Co zjistíme nejdřív?',a:['Počet dětí ve všech skupinách.','Konečný počet bez mezikroku.'],ok:0}));});
window.grade5Model={topics:topics,tasks:tasks};
})();