'use strict';
// Ten explicitly bounded variants per introductory concept. IDs preserve earlier progress.
window.makeMission=function(w,m,original){
 const t={...original,story:[...original.story],paths:[...original.paths],explain:[...original.explain]};
 if(w===0)return t;
 const f=n=>Number(n.toFixed(4)).toLocaleString('cs-CZ');
 if(w===1||w===2){
 const pairs=w===1?[[4,3],[2,3],[3,2],[5,2],[4,2],[2,4],[3,3],[5,3],[4,4],[3,4]]:[[6,4],[4,3],[5,4],[6,3],[4,5],[5,5],[6,5],[4,6],[5,6],[6,6]];
 const [n,k]=pairs[m];Object.assign(t,{n,k,answer:n*k});
 t.story=w===1?[`Chystáme svačinu pro děti. Ke stolu jich přijde ${n}.`,`Každé dítě dostane ${k} rohlíky.`]:[`Na zahradě máme záhony s rajčaty. Záhonů je celkem ${n}.`,`Na každém záhonu roste ${k} sazenic rajčat.`];
 if(w===2)t.story[1]=`Na každém záhonu ${k<5?'rostou':'roste'} ${k} ${k<5?'sazenice':'sazenic'} rajčat.`;
 t.question=w===1?'Kolik rohlíků potřebujeme pro všechny děti?':'Kolik sazenic rajčat roste na všech záhonech dohromady?';
 t.paths=[`Vynásobím ${n} × ${k}.`,`Sečtu ${Array(n).fill(k).join(' + ')}.`,`Sečtu ${n} + ${k}.`];
 t.explain=[`Máme ${n} stejně velkých skupin. Počet položek v každé skupině je ${k}. Celkový počet zapíšu jako ${n} × ${k}.`,`Počet v každé skupině zapíšu zvlášť a všechny skupiny sečtu: ${Array(n).fill(k).join(' + ')}.`,`Součet ${n} + ${k} míchá počet skupin s počtem v jedné skupině. Vyzkoušej rozdělení: potřebujeme ${n} skupin a v každé ${k} položky.`];
 t.check=w===1?`Rozdělím rohlíky mezi všechny děti. Každé musí dostat přesně ${k} rohlíky.`:`Rozmístím sazenice na všechny záhony. Počet na každém záhonu musí být ${k}.`;
 t.model=w===1?`Každé dítě má svůj talíř. Na každý talíř patří ${k} rohlíky.`:`Každý záhon tvoří jednu skupinu. Počet sazenic v každé skupině je ${k}.`;
 }
 if(w===3){const [a,b,g]=[[8,5,2],[9,6,2],[10,7,3],[12,5,2],[11,8,3],[14,6,2],[15,9,3],[16,7,2],[18,8,4],[20,10,4]][m];Object.assign(t,{a,b,g,answer:2*(a+b)-g});t.story=[`U domu je obdélníková zahrada. Je dlouhá ${a} metrů a široká ${b} metrů.`,`Kolem zahrady chceme postavit plot. V místě branky široké ${g} metry plot nebude.`];t.paths=['Sečtu všechny čtyři strany a odečtu šířku branky.',`Spočtu 2 × (${a} + ${b}) − ${g}.`,`Spočtu ${a} × ${b} − ${g}.`];t.explain=[`Délky stran jsou ${a}, ${b}, ${a} a ${b} metrů. Branka nahradí ${g} metry plotu.`,`Obdélník má dva páry stejně dlouhých stran. Sečtu délku a šířku, součet zdvojnásobím a odečtu branku.`,`Součin ${a} × ${b} popisuje obsah zahrady. Plot však vede po jejím okraji; hledáme délku.`];t.check=`Délka plotu musí být o ${g} metry menší než celý obvod zahrady.`;t.model=`Plot tvoří čtyři strany zahrady, kromě místa pro branku.`;}
 if(w===4){const v=[65,40,80,100,120,60,140,160,180,150][m];Object.assign(t,{litres:v,answer:v/4,badcheck:"Počet litrů je vždy stejný jako výška hladiny v centimetrech."});t.story=[`Akvárium má vnitřní délku 100 cm, šířku 40 cm a výšku 50 cm. Uvnitř není písek ani žádné dekorace.`,`Do prázdného akvária nalijeme ${v} litrů vody.`];t.explain=[`${v} litrů je ${v*1000} cm³. Objem vydělím obsahem dna 4 000 cm². Výšku získám v centimetrech.`,`${v} litrů je ${v} dm³. Dno má rozměry 10 dm a 4 dm. Objem vydělím obsahem dna 40 dm². Výšku v decimetrech pak převedu na centimetry.`,`Součet délky a šířky není obsah dna. Voda pokrývá celé dno, takže potřebujeme jeho obsah.`];t.paths[2]=`Vydělím ${v} součtem 100 + 40.`;t.check=`Vrstva vysoká 1 cm pojme 4 litry. Vypočtenou výšku v centimetrech vynásobím čtyřmi a musím dostat ${v} litrů.`;}
 if(w===5){const [n,scale]=[[8,25000],[4,25000],[6,50000],[5,20000],[12,25000],[7,50000],[9,20000],[10,50000],[3,100000],[6,100000]][m];Object.assign(t,{n,scale,answer:n*scale/100000});t.story=[`Na mapě měří vybraná železniční trať ${n} cm. Chceme zjistit její skutečnou délku.`,`Měřítko mapy je 1 : ${scale}. Jeden centimetr na mapě tedy představuje ${scale} cm ve skutečnosti.`];t.paths=[`Vynásobím ${n} × ${scale} a převedu centimetry na kilometry.`,`Zjistím skutečnou délku pro 1 cm mapy a vynásobím ji číslem ${n}.`,`Vydělím ${n} číslem ${scale}.`];t.explain=[`Výpočet ${n} × ${scale} dává délku ve skutečnosti v centimetrech. Kilometr má 100 000 centimetrů.`,`Jeden centimetr mapy představuje ${scale/100} metrů. Potřebujeme ${n} takových úseků. Výsledek převedu na kilometry.`,`Dělením dostaneš ještě menší číslo. Skutečná trať je ale mnohem delší než její obraz na mapě.`];t.check=`Skutečná délka musí odpovídat ${n} úsekům, z nichž každý měří ${scale/100} metrů.`;t.model=`Měřítko říká, kolikrát je skutečná délka větší než délka na mapě.`;}
 if(w===6){const [base,p]=[[800,15],[600,10],[1000,20],[400,25],[1200,15],[500,30],[900,20],[1600,25],[700,10],[2000,35]][m],loss=base*p/100,left=base-loss;Object.assign(t,{base,loss,left,answer:p});t.story=[`Veřejné osvětlení dříve spotřebovalo každý den ${base} kWh elektrické energie.`,`Po výměně lamp spotřebuje za den ${left} kWh. Úsporu chceme porovnat s původní spotřebou.`];t.explain=[`Úspora je ${base} − ${left} = ${loss} kWh. Vydělím ji původní spotřebou ${base} kWh a vynásobím stem.`,`Nejprve spočtu, kolik procent původní spotřeby zůstalo: ${left} ÷ ${base} × 100. Výsledek odečtu od 100 %.`,`Nová spotřeba ${left} kWh není v této otázce základem. Procenta úspory se vztahují k původním ${base} kWh.`];t.check=`Jedno procento původní spotřeby je ${f(base/100)} kWh. Vynásobím je vypočteným počtem procent a musím dostat úsporu ${loss} kWh.`;t.model=`Původních ${base} kWh je celý základ, tedy 100 %.`;}
 if(w===7){const [a,b,c]=[[3,4,5],[6,8,10],[5,12,13],[9,12,15],[8,15,17],[12,16,20],[7,24,25],[15,20,25],[10,24,26],[20,21,29]][m];Object.assign(t,{a,b,answer:c});t.story=[`U hvězdárny je plošina ve výšce ${b} metrů nad vodorovnou zemí. Stěna pod ní je svislá.`,`K plošině postavíme žebřík. Jeho dolní konec bude na zemi ${a} metrů od stěny. Hledáme geometrickou délku mezi těmito body.`];t.paths=[`Použiju Pythagorovu větu: odmocnina z (${a}² + ${b}²).`,`Vyzkouším délku ${c} metrů a ověřím ji Pythagorovou větou.`,`Sečtu ${a} + ${b}.`];t.explain=[`Žebřík je přepona pravoúhlého trojúhelníku. Druhou mocninu jeho délky získám jako ${a}² + ${b}². Potom odmocním.`,`Ověřím, zda ${a}² + ${b}² = ${c}². Pokud rovnost platí, vybraná délka odpovídá trojúhelníku.`,`Součet ${a} + ${b} měří cestu po zemi a pak vzhůru podél stěny. Žebřík spojuje oba body přímo.`];t.check=`Žebřík musí být delší než ${b} metrů, ale kratší než cesta po zemi a podél stěny: ${a+b} metrů.`;t.model=`Vodorovná vzdálenost ${a} m a svislá výška ${b} m jsou odvěsny. Žebřík tvoří přeponu.`;}
 if(w===8){const [a,b,r,s]=[[100,200,4,2],[120,180,4,2],[80,200,5,2],[150,250,4,2],[100,250,5,2],[120,240,4,2],[60,180,5,3],[100,260,4,2],[150,300,5,2],[80,280,5,3]][m];Object.assign(t,{feeA:a,feeB:b,rateA:r,rateB:s,answer:(b-a)/(r-s)});t.story=[`Vybíráme mezi dvěma nabídkami telefonního operátora. U nabídky A zaplatíme každý měsíc ${a} Kč a k tomu ${r} Kč za každou provolanou minutu.`,`U nabídky B zaplatíme každý měsíc ${b} Kč a k tomu ${s} Kč za každou provolanou minutu. Žádné další poplatky nepočítáme.`];t.explain=[`Počet minut označím x. Porovnám celkové ceny: ${a} + ${r}x = ${b} + ${s}x.`,`U nabídky B zaplatím za měsíční poplatek o ${b-a} Kč více. Za každou minutu ale ušetřím ${r-s} Kč. Zjistím, za kolik minut se rozdíl vyrovná.`,`Při 100 minutách stojí nabídka A ${a+100*r} Kč a B ${b+100*s} Kč. Samotný měsíční poplatek tedy neříká, která nabídka vyjde levněji při každém počtu minut.`];t.model=`A: ${a} + ${r} × počet minut. B: ${b} + ${s} × počet minut.`;}
 return t;
};
