'use strict';
(()=>{
  const districts={
    celaCisla:{name:'Číselná osa',short:'Celá čísla',accent:'#60a5fa',icon:'numberline',rewards:['Nulový bod','První úsek vpravo','První úsek vlevo','Kladná strana','Záporná strana','Ukazatele vzdálenosti','Osvětlení osy','Rozhledna osy','Chodci na ose','Osa v pohybu']},
    zlomky:{name:'Zlomkový trh',short:'Zlomky',accent:'#fb923c',icon:'pie',rewards:['První stánek','Váhy na zlomky','Krájecí pult','Regál se zlomky','Ochutnávkový stůl','Tržní světla','Informační tabule','Stan pro návštěvníky','Prodejci a kupci','Trh v plném ruchu']},
    pomer:{name:'Vážní dvůr',short:'Poměr',accent:'#34d399',icon:'scale',rewards:['První váha','Závaží A','Závaží B','Vyrovnávací rameno','Kontrolní stůl','Dvorní světla','Skladiště závaží','Vrátnice','Vážní mistři','Dvůr v provozu']},
    umernost:{name:'Úměrná dráha',short:'Přímá a nepřímá úměrnost',accent:'#c084fc',icon:'rail',rewards:['První kolej','Druhá kolej','Návěstidlo','Nástupiště','Stoupající trať','Klesající trať','Traťová světla','Přijíždějící vlak','Cestující','Dráha v pohybu']},
    procenta:{name:'Procentová pekárna',short:'Procenta',accent:'#fbbf24',icon:'percent',rewards:['Pec','První bochník','Váha na těsto','Regál s pečivem','Prodejní pult','Pekárenská světla','Cedule se slevou','Čekárna zákazníků','Pekaři a zákazníci','Pekárna v plném provozu']},
    trojuhelniky:{name:'Trojúhelníková čtvrť',short:'Trojúhelníky',accent:'#f87171',icon:'triangle',rewards:['První vrchol','Druhý vrchol','Třetí vrchol','Spojnice stran','Výšková věž','Čtvrťová světla','Rozhledna','Návštěvníci čtvrti','Sochy na vrcholech','Čtvrť v plném lesku']},
    ctyruhelniky:{name:'Čtyřúhelníková zahrada',short:'Čtyřúhelníky',accent:'#4ade80',icon:'quad',rewards:['První záhon','Druhý záhon','Rovnoběžné cesty','Lichoběžníkový trávník','Zahradní altán','Zahradní světla','Fontána','Zahradníci','Návštěvníci zahrady','Zahrada v plném květu']},
    soumernost:{name:'Zrcadlová alej',short:'Osová a středová souměrnost',accent:'#22d3ee',icon:'mirror',rewards:['První zrcadlo','Druhé zrcadlo','Osa souměrnosti','Odražené sochy','Lucerny aleje','Vodní hladina','Rozhledna','Procházející lidé','Zrcadlové dvojice','Alej v plné kráse']},
    desetinnaCisla:{name:'Přesná dílna',short:'Desetinná čísla',accent:'#fb7185',icon:'gauge',rewards:['Pracovní stůl','Přesné váhy','Měřicí pásmo','Kalibrovací stanice','Regál s díly','Dílenská světla','Kontrolní hodiny','Mistři dílny','Zákazníci dílny','Dílna v plném provozu']},
    slozene:{name:'Ústřední náměstí',short:'Vícekrokové úlohy',accent:'#f472b6',icon:'hub',rewards:['První dlažba','Druhá dlažba','Kašna','Sochy náměstí','Podloubí','Noční osvětlení','Tržní stánek','Lavičky','Obyvatelé náměstí','Náměstí v plném ruchu']}
  };
  const order=Object.keys(districts);
  const ids=progress=>new Set(Array.isArray(progress)?progress:[]);
  function topicCount(topicId,progress){const completed=ids(progress);let n=0;for(let i=1;i<=10;i++)if(completed.has(`g7-${topicId}-${String(i).padStart(2,'0')}`))n++;return n}
  function icon(type){
    const icons={numberline:'<path d="M15 45h70"/><path d="M30 39v12M50 39v12M70 39v12"/><circle cx="30" cy="45" r="5"/><circle cx="70" cy="45" r="5"/>',pie:'<circle cx="50" cy="47" r="28"/><path d="M50 47L50 19M50 47L74 61M50 47L26 61"/>',scale:'<path d="M50 20v50M30 30h40M30 30l-8 20h16zM70 30l-8 20h16z"/><path d="M20 70h60"/>',rail:'<path d="M15 65h70M15 55h70"/><path d="M22 55v10M37 55v10M52 55v10M67 55v10"/><path d="M20 25L75 40"/>',percent:'<circle cx="30" cy="30" r="9"/><circle cx="70" cy="64" r="9"/><path d="M72 20L28 74"/>',triangle:'<path d="M50 18L84 72H16z"/><path d="M26 68a12 12 0 0 1 10-9M74 68a12 12 0 0 0-10-9"/>',quad:'<path d="M20 65h40l20-40H40z"/>',mirror:'<path d="M50 15v60" stroke-dasharray="4 5"/><path d="M45 70L30 30h10l5 40z"/><path d="M55 70L70 30h-10l-5 40z"/>',gauge:'<path d="M20 65a30 30 0 0 1 60 0"/><path d="M50 65L68 40"/><circle cx="50" cy="65" r="4"/>',hub:'<circle cx="50" cy="47" r="8"/><path d="M50 39V15M50 55v24M42 47H18M58 47h24"/>'};
    return `<svg viewBox="0 0 100 90" aria-hidden="true">${icons[type]}</svg>`;
  }
  function district(topicId,progress,selected){const d=districts[topicId],count=topicCount(topicId,progress),done=count===10;return `<button class="city-district progress-${count} ${selected===topicId?'selected':''} ${done?'complete':''}" data-city-topic="${topicId}" style="--accent:${d.accent}" aria-label="${d.name}: ${count} z 10 dokončeno"><span class="district-sky"><i class="orb feature f10"></i><i class="cloud cloud-a feature f2"></i><i class="cloud cloud-b feature f7"></i></span><span class="district-land"><i class="building main feature f1"></i><i class="building side feature f3"></i><i class="bridge feature f4"></i><i class="nature n1 feature f5"></i><i class="nature n2 feature f6"></i><i class="light l1 feature f2"></i><i class="light l2 feature f8"></i><i class="person p1 feature f9"></i><i class="person p2 feature f9"></i><i class="motion feature f10"></i></span><span class="district-icon">${icon(d.icon)}</span><span class="district-copy"><b>${d.name}</b><small>${d.short}</small><em>${count}/10</em></span><span class="district-complete">ČTVRŤ OŽILA</span></button>`}
  function render(progress,selected='all'){const total=Array.from(ids(progress)).filter(id=>/^g7-/.test(id)).length;return `<section class="city-world ${total===100?'world-complete':''}" aria-label="Souměrné město, herní svět 7. ročníku"><div class="city-heading"><div><span class="eyebrow">HERNÍ SVĚT 7. ROČNÍKU</span><h1>Souměrné město</h1><p>Každá dokončená úloha probudí další část vyváženého města. Vyber si čtvrť v libovolném pořadí.</p></div><div class="city-total"><strong>${total}</strong><span>ze 100 prvků žije</span></div></div><div class="city-board">${order.map(id=>district(id,progress,selected)).join('')}<div class="city-river" aria-hidden="true"><i></i><i></i><i></i></div><div class="city-core" aria-hidden="true"><span></span></div></div>${total===100?'<div class="world-finale"><b>Město je v rovnováze.</b> Propojil jsi všech sto příběhů, modelů, postupů a kontrol reality.</div>':''}</section>`}
  function mini(topicId,progress,taskOrder){const d=districts[topicId],count=topicCount(topicId,progress),reward=d.rewards[(taskOrder||1)-1];return `<section class="district-mini" style="--accent:${d.accent}"><div class="mini-art">${district(topicId,progress,topicId)}</div><div><span class="eyebrow">${d.name}</span><h3>${count}/10 prvků probuzeno</h3><p>${count===10?'Celá čtvrť žije.':`Za tuto úlohu čeká: ${reward}.`}</p></div></section>`}
  function nextUndone(topicId,currentId,progress,tasks){const completed=ids(progress),same=tasks.filter(t=>t.topicId===topicId),at=Math.max(0,same.findIndex(t=>t.id===currentId));for(let step=1;step<=same.length;step++){const task=same[(at+step)%same.length];if(!completed.has(task.id))return task}return null}
  window.grade7World={districts,order,topicCount,render,mini,nextUndone};
})();
