'use strict';
(()=>{
  const districts={
    percentages:{name:'Solární terasy',short:'Procenta',accent:'#ffc857',icon:'sun',rewards:['Rozsvícené slunce','První solární pole','Druhé solární pole','Zelená střecha','Nabíjecí stanice','Větrná turbína','Energetická věž','Světelná lávka','Obyvatelé teras','Energetický festival']},
    equations:{name:'Věž rovnováhy',short:'Rovnice',accent:'#ff7b72',icon:'balance',rewards:['Levé křídlo','Pravé křídlo','Spojovací most','Spodní okna','Horní okna','Výtah','Střešní zahrada','Signální světlo','Návštěvníci věže','Světelná koruna']},
    systems:{name:'Dvojměstí',short:'Soustavy rovnic',accent:'#a78bfa',icon:'towers',rewards:['První věž','Druhá věž','Společné náměstí','Spojovací dráha','Vodní kanál','Dolní světla','Horní světla','Městský vlak','Obyvatelé náměstí','Spojené panorama']},
    ratio:{name:'Zahrady poměru',short:'Poměr a úměrnost',accent:'#67e8a5',icon:'leaf',rewards:['První strom','Druhý strom','Skleník','Zavlažovací kanál','Květinové pole','Ovocný sad','Pěší stezka','Zahradníci','Noční lucerny','Rozkvetlé zahrady']},
    functions:{name:'Datové nádraží',short:'Funkce a grafy',accent:'#5eead4',icon:'graph',rewards:['Osa nádraží','První bod trasy','Druhý bod trasy','Stoupající trať','Klesající trať','Nástupiště','Signální věž','Přijíždějící vlak','Cestující','Síť v pohybu']},
    finance:{name:'Obchodní přístav',short:'Finance',accent:'#fbbf24',icon:'coin',rewards:['Molo','První obchod','Druhý obchod','Jeřáb','Nákladní loď','Sklad','Maják','Tržní stánky','Posádka přístavu','Živý přístav']},
    geometry:{name:'Architektonická čtvrť',short:'Geometrie',accent:'#fb7185',icon:'shapes',rewards:['Trojúhelníkový dům','Kruhový pavilon','Pravoúhlá věž','Klenutý most','Mozaikové náměstí','Vyhlídka','Park geometrů','Pouliční světla','Návštěvníci','Zářící architektura']},
    volume:{name:'Vodní laboratoře',short:'Objem a převody',accent:'#60a5fa',icon:'drop',rewards:['První nádrž','Vodní věž','Průhledná laboratoř','Potrubí','Čerpací stanice','Vodopád','Plovoucí zahrada','Výzkumná loď','Badatelé','Pulzující vodní okruh']},
    data:{name:'Observatoř dat',short:'Data a pravděpodobnost',accent:'#c084fc',icon:'stars',rewards:['Kopule','První hvězda','Souhvězdí','Datová anténa','Měřicí stanice','Výpočetní centrum','Pozorovací terasa','Družice','Výzkumníci','Noční obloha']},
    multistep:{name:'Centrum souvislostí',short:'Vícekrokové úlohy',accent:'#f97316',icon:'core',rewards:['Základy centra','První patro','Druhé patro','Propojovací most','Centrální strom','Energetický kruh','Velká knihovna','Náměstí','Obyvatelé centra','Srdce celého města']}
  };
  const order=Object.keys(districts);
  const ids=progress=>new Set(Array.isArray(progress)?progress:[]);
  function topicCount(topicId,progress){const completed=ids(progress);let n=0;for(let i=1;i<=10;i++)if(completed.has(`g9-${topicId}-${String(i).padStart(2,'0')}`))n++;return n}
  function icon(type){
    const icons={sun:'<circle cx="50" cy="44" r="13"/><path d="M50 17v10M50 61v10M23 44h10M67 44h10M31 25l7 7M62 56l7 7M69 25l-7 7M38 56l-7 7"/>',balance:'<path d="M50 22v49M31 72h38M27 35h46M36 35l-12 22h24L36 35zm28 0L52 57h24L64 35z"/>',towers:'<path d="M20 72V29h24v43M56 72V18h24v54M27 39h10M27 50h10M63 29h10M63 40h10M44 49h12"/>',leaf:'<path d="M22 65C25 31 48 20 77 23c0 31-20 52-55 42zM28 60c16-13 28-20 44-29"/>',graph:'<path d="M20 72V22M20 72h62M27 62l15-15 12 8 21-27M69 28h6v6"/>',coin:'<ellipse cx="50" cy="47" rx="28" ry="22"/><path d="M50 31v32M60 36c-4-5-20-6-20 3 0 10 20 5 20 15 0 9-16 8-21 3"/>',shapes:'<circle cx="31" cy="52" r="15"/><rect x="53" y="37" width="27" height="27"/><path d="M50 20l15 13H35l15-13z"/>',drop:'<path d="M50 17S27 43 27 57a23 23 0 0046 0c0-14-23-40-23-40zM38 59c2 7 7 10 14 10"/>',stars:'<path d="M50 19l6 17 18 1-14 11 5 18-15-10-15 10 5-18-14-11 18-1 6-17z"/>',core:'<circle cx="50" cy="48" r="24"/><circle cx="50" cy="48" r="10"/><path d="M50 16v12M50 68v12M18 48h12M70 48h12"/>'};
    return `<svg viewBox="0 0 100 90" aria-hidden="true">${icons[type]}</svg>`;
  }
  function district(topicId,progress,selected){const d=districts[topicId],count=topicCount(topicId,progress),done=count===10;return `<button class="city-district progress-${count} ${selected===topicId?'selected':''} ${done?'complete':''}" data-city-topic="${topicId}" style="--accent:${d.accent}" aria-label="${d.name}: ${count} z 10 dokončeno"><span class="district-sky"><i class="orb feature f10"></i><i class="cloud cloud-a feature f2"></i><i class="cloud cloud-b feature f7"></i></span><span class="district-land"><i class="building main feature f1"></i><i class="building side feature f3"></i><i class="bridge feature f4"></i><i class="nature n1 feature f5"></i><i class="nature n2 feature f6"></i><i class="light l1 feature f2"></i><i class="light l2 feature f8"></i><i class="person p1 feature f9"></i><i class="person p2 feature f9"></i><i class="motion feature f10"></i></span><span class="district-icon">${icon(d.icon)}</span><span class="district-copy"><b>${d.name}</b><small>${d.short}</small><em>${count}/10</em></span><span class="district-complete">OKRUH OŽIL</span></button>`}
  function render(progress,selected='all'){const total=Array.from(ids(progress)).filter(id=>/^g9-/.test(id)).length;return `<section class="city-world ${total===100?'world-complete':''}" aria-label="Město souvislostí, herní svět 9. ročníku"><div class="city-heading"><div><span class="eyebrow">HERNÍ SVĚT 9. ROČNÍKU</span><h1>Město souvislostí</h1><p>Každá dokončená úloha probudí konkrétní část města. Vyber si čtvrť v libovolném pořadí.</p></div><div class="city-total"><strong>${total}</strong><span>ze 100 prvků žije</span></div></div><div class="city-board">${order.map(id=>district(id,progress,selected)).join('')}<div class="city-river" aria-hidden="true"><i></i><i></i><i></i></div><div class="city-core" aria-hidden="true"><span></span></div></div>${total===100?'<div class="world-finale"><b>Město žije.</b> Propojil jsi všech sto příběhů, modelů, postupů a kontrol reality.</div>':''}</section>`}
  function mini(topicId,progress,taskOrder){const d=districts[topicId],count=topicCount(topicId,progress),reward=d.rewards[(taskOrder||1)-1];return `<section class="district-mini" style="--accent:${d.accent}"><div class="mini-art">${district(topicId,progress,topicId)}</div><div><span class="eyebrow">${d.name}</span><h3>${count}/10 prvků probuzeno</h3><p>${count===10?'Celá čtvrť žije.':`Za tuto úlohu čeká: ${reward}.`}</p></div></section>`}
  function nextUndone(topicId,currentId,progress,tasks){const completed=ids(progress),same=tasks.filter(t=>t.topicId===topicId),at=Math.max(0,same.findIndex(t=>t.id===currentId));for(let step=1;step<=same.length;step++){const task=same[(at+step)%same.length];if(!completed.has(task.id))return task}return null}
  window.grade9World={districts,order,topicCount,render,mini,nextUndone};
})();
