'use strict';
(()=>{
  const districts={
    mocniny:{name:'Věž mocnin',short:'Mocniny a odmocniny',accent:'#eab308',icon:'power',rewards:['Základ věže','První patro','Zdvojená hladina','Krystalová anténa','Odmocninová studna','Věžní hodiny','Vyhlídková plošina','Zářící špice','Návštěvníci věže','Rozzářená věž']},
    vyrazy:{name:'Dílna vzorců',short:'Výrazy a mnohočleny',accent:'#f97316',icon:'expr',rewards:['Pracovní stůl','První vzorec na tabuli','Regál s mnohočleny','Rozkladový lis','Sestavovací pás','Vzorcová tabule','Zkušební stanice','Dílenská světla','Mistři dílny','Živá dílna']},
    rovnice:{name:'Rovnovážný most',short:'Lineární rovnice',accent:'#38bdf8',icon:'balance',rewards:['První pilíř','Druhý pilíř','Nosník mostu','Vyvážená lávka','Zábradlí','Majáky mostu','Kontrolní budka','Slavnostní osvětlení','Chodci na mostě','Most v rovnováze']},
    nerovnice:{name:'Schodiště nerovnic',short:'Nerovnice',accent:'#a3e635',icon:'compare',rewards:['První schod','Zábradlí schodiště','Stoupající rameno','Klesající rameno','Odpočívadlo','Směrové šipky','Lucerny schodiště','Vyhlídka nahoře','Kolemjdoucí','Schodiště v pohybu']},
    pythagoras:{name:'Pravoúhlé nábřeží',short:'Pythagorova věta',accent:'#fb923c',icon:'triangle',rewards:['Základový kámen','První nábřežní zeď','Žebřík k plošině','Pravoúhlý roh','Kotviště','Nábřežní lampy','Rozhledna','Odrazový můstek','Návštěvníci nábřeží','Nábřeží v plném lesku']},
    kruh:{name:'Kruhové náměstí',short:'Kruh a kružnice',accent:'#f472b6',icon:'circle',rewards:['Dlažba náměstí','První kašna','Kruhový záhon','Obvodová lavička','Sluneční hodiny','Kruhové osvětlení','Altán','Fontána','Obyvatelé náměstí','Náměstí v pohybu']},
    hranoly:{name:'Hranolové sklady',short:'Povrch a objem těles',accent:'#818cf8',icon:'box',rewards:['Základy skladu','První regál','Krychlové bedny','Nakládací rampa','Jeřáb','Skladová světla','Kontrolní věž','Expediční brána','Skladníci','Sklady v plném provozu']},
    statistika:{name:'Diagramové trhy',short:'Statistika a diagramy',accent:'#2dd4bf',icon:'bars',rewards:['První stánek','Sloupcový stánek','Koláčový stánek','Vývěska dat','Váhy trhu','Tržní světla','Informační tabule','Stan pro návštěvníky','Prodejci a kupci','Trh v plném ruchu']},
    procenta:{name:'Úrokové centrum',short:'Procenta a úroky',accent:'#facc15',icon:'percent',rewards:['Vstupní hala','První přepážka','Trezor','Úročící stroj','Slevové okénko','Informační displej','Bezpečnostní světla','Zasedací sál','Klienti centra','Centrum v provozu']},
    slozene:{name:'Křižovatka úloh',short:'Vícekrokové úlohy',accent:'#fb7185',icon:'link',rewards:['První cesta','Druhá cesta','Rozcestník','Spojovací kruh','Semafory','Noční osvětlení','Zastávka','Info tabule','Chodci na křižovatce','Křižovatka v plném provozu']}
  };
  const order=Object.keys(districts);
  const ids=progress=>new Set(Array.isArray(progress)?progress:[]);
  function topicCount(topicId,progress){const completed=ids(progress);let n=0;for(let i=1;i<=10;i++)if(completed.has(`g8-${topicId}-${String(i).padStart(2,'0')}`))n++;return n}
  function icon(type){
    const icons={power:'<rect x="22" y="32" width="34" height="34" rx="4"/><rect x="60" y="14" width="18" height="18" rx="3"/>',expr:'<path d="M32 18c-11 9-11 45 0 54M68 18c11 9 11 45 0 54"/><circle cx="50" cy="45" r="4"/>',balance:'<path d="M50 22v49M31 72h38M27 35h46M36 35l-12 22h24L36 35zm28 0L52 57h24L64 35z"/>',compare:'<path d="M64 20L29 45l35 25M23 60h54"/>',triangle:'<path d="M20 70h60L20 20v50z"/><path d="M20 58h12v12"/>',circle:'<circle cx="50" cy="47" r="28"/><path d="M22 47h56M50 19v56"/>',box:'<path d="M20 32l30-14 30 14-30 14-30-14zM20 32v28l30 14M80 32v28L50 74M50 46v28"/>',bars:'<path d="M20 72V22M20 72h60M32 60v12M46 46v26M60 34v38M74 50v22"/>',percent:'<circle cx="32" cy="32" r="9"/><circle cx="68" cy="62" r="9"/><path d="M70 22L30 72"/>',link:'<circle cx="26" cy="26" r="9"/><circle cx="74" cy="26" r="9"/><circle cx="50" cy="68" r="9"/><path d="M33 30l14 30M67 30L53 60"/>'};
    return `<svg viewBox="0 0 100 90" aria-hidden="true">${icons[type]}</svg>`;
  }
  function district(topicId,progress,selected){const d=districts[topicId],count=topicCount(topicId,progress),done=count===10;return `<button class="city-district progress-${count} ${selected===topicId?'selected':''} ${done?'complete':''}" data-city-topic="${topicId}" style="--accent:${d.accent}" aria-label="${d.name}: ${count} z 10 dokončeno"><span class="district-sky"><i class="orb feature f10"></i><i class="cloud cloud-a feature f2"></i><i class="cloud cloud-b feature f7"></i></span><span class="district-land"><i class="building main feature f1"></i><i class="building side feature f3"></i><i class="bridge feature f4"></i><i class="nature n1 feature f5"></i><i class="nature n2 feature f6"></i><i class="light l1 feature f2"></i><i class="light l2 feature f8"></i><i class="person p1 feature f9"></i><i class="person p2 feature f9"></i><i class="motion feature f10"></i></span><span class="district-icon">${icon(d.icon)}</span><span class="district-copy"><b>${d.name}</b><small>${d.short}</small><em>${count}/10</em></span><span class="district-complete">STAVBA HOTOVA</span></button>`}
  function render(progress,selected='all'){const total=Array.from(ids(progress)).filter(id=>/^g8-/.test(id)).length;return `<section class="city-world ${total===100?'world-complete':''}" aria-label="Konstrukční město, herní svět 8. ročníku"><div class="city-heading"><div><span class="eyebrow">HERNÍ SVĚT 8. ROČNÍKU</span><h1>Konstrukční město</h1><p>Každá dokončená úloha postaví další část technického města. Vyber si čtvrť v libovolném pořadí.</p></div><div class="city-total"><strong>${total}</strong><span>ze 100 prvků stojí</span></div></div><div class="city-board">${order.map(id=>district(id,progress,selected)).join('')}<div class="city-river" aria-hidden="true"><i></i><i></i><i></i></div><div class="city-core" aria-hidden="true"><span></span></div></div>${total===100?'<div class="world-finale"><b>Město je postavené.</b> Zvládl jsi všech sto konstrukcí, vzorců, postupů a kontrol reality.</div>':''}</section>`}
  function mini(topicId,progress,taskOrder){const d=districts[topicId],count=topicCount(topicId,progress),reward=d.rewards[(taskOrder||1)-1];return `<section class="district-mini" style="--accent:${d.accent}"><div class="mini-art">${district(topicId,progress,topicId)}</div><div><span class="eyebrow">${d.name}</span><h3>${count}/10 prvků postaveno</h3><p>${count===10?'Celá čtvrť je hotová.':`Za tuto úlohu čeká: ${reward}.`}</p></div></section>`}
  function nextUndone(topicId,currentId,progress,tasks){const completed=ids(progress),same=tasks.filter(t=>t.topicId===topicId),at=Math.max(0,same.findIndex(t=>t.id===currentId));for(let step=1;step<=same.length;step++){const task=same[(at+step)%same.length];if(!completed.has(task.id))return task}return null}
  window.grade8World={districts,order,topicCount,render,mini,nextUndone};
})();
