'use strict';
(()=>{
const districts={
cisla:{name:'Číselné domečky',short:'Čísla do 100',accent:'#60a5fa',icon:'numberline'},
scitani:{name:'Sčítací hřiště',short:'Sčítání',accent:'#34d399',icon:'hub'},
odcitani:{name:'Ubývající cesta',short:'Odčítání',accent:'#fbbf24',icon:'rail'},
nasobeni:{name:'Skupinková louka',short:'Násobení',accent:'#fb923c',icon:'cube'},
deleni:{name:'Dělicí piknik',short:'Rozdělování',accent:'#f472b6',icon:'pie'},
porovnani:{name:'Porovnávací most',short:'Porovnávání',accent:'#22d3ee',icon:'gauge'},
jednotky:{name:'Měřicí dílna',short:'Jednotky',accent:'#c084fc',icon:'mirror'},
cas:{name:'Hodinová věž',short:'Čas',accent:'#4ade80',icon:'gauge'},
penize:{name:'Malý obchůdek',short:'Peníze',accent:'#fb7185',icon:'quad'},
vicekrokove:{name:'Příběhová stezka',short:'Dva kroky',accent:'#f87171',icon:'triangle'}};
const rewards=['První část','Druhý prvek','Nové místo','Další stavba','Výzdoba','Světla','Cesta','Postava','Návštěvníci','Celá čtvrť'];
Object.keys(districts).forEach(id=>districts[id].rewards=rewards.map((x,i)=>x+' '+(i+1)));
const order=Object.keys(districts),ids=p=>new Set(Array.isArray(p)?p:[]);
function topicCount(topicId,progress){const s=ids(progress);let n=0;for(let i=1;i<=10;i++)if(s.has('g2-'+topicId+'-'+String(i).padStart(2,'0')))n++;return n}
function icon(type){const x={numberline:'<path d="M15 45h70"/><path d="M25 39v12M40 39v12M55 39v12M70 39v12"/>',hub:'<circle cx="50" cy="47" r="8"/><path d="M50 39V15M50 55v24M42 47H18M58 47h24"/>',cube:'<path d="M30 30l20-12 20 12v30L50 72 30 60z"/><path d="M30 30l20 12 20-12M50 42v30"/>',rail:'<path d="M15 65h70M15 55h70"/><path d="M22 55v10M37 55v10M52 55v10M67 55v10"/>',pie:'<circle cx="50" cy="47" r="28"/><path d="M50 47L50 19M50 47L74 61M50 47L26 61"/>',gauge:'<path d="M20 65a30 30 0 0 1 60 0"/><path d="M50 65L68 40"/>',mirror:'<path d="M50 15v60" stroke-dasharray="4 5"/><path d="M35 30h10v40H35M55 30h10v40H55"/>',quad:'<path d="M20 65h40l20-40H40z"/>',triangle:'<path d="M50 18L84 72H16z"/>'};return '<svg viewBox="0 0 100 90" aria-hidden="true">'+x[type]+'</svg>'}
function district(topicId,progress,selected){const d=districts[topicId],count=topicCount(topicId,progress),done=count===10;return '<button class="city-district progress-'+count+' '+(selected===topicId?'selected':'')+' '+(done?'complete':'')+'" data-city-topic="'+topicId+'" style="--accent:'+d.accent+'" aria-label="'+d.name+': '+count+' z 10 dokončeno"><span class="district-sky"><i class="orb feature f10"></i><i class="cloud cloud-a feature f2"></i><i class="cloud cloud-b feature f7"></i></span><span class="district-land"><i class="building main feature f1"></i><i class="building side feature f3"></i><i class="bridge feature f4"></i><i class="nature n1 feature f5"></i><i class="nature n2 feature f6"></i><i class="light l1 feature f2"></i><i class="light l2 feature f8"></i><i class="person p1 feature f9"></i><i class="person p2 feature f9"></i><i class="motion feature f10"></i></span><span class="district-icon">'+icon(d.icon)+'</span><span class="district-copy"><b>'+d.name+'</b><small>'+d.short+'</small><em>'+count+'/10</em></span><span class="district-complete">ČTVRŤ OŽILA</span></button>'}
function render(progress,selected='all'){const total=Array.from(ids(progress)).filter(id=>/^g2-/.test(id)).length;return '<section class="city-world '+(total===100?'world-complete':'')+'" aria-label="Pohádkové městečko, herní svět 3. ročníku"><div class="city-heading"><div><span class="eyebrow">HERNÍ SVĚT 2. ROČNÍKU</span><h1>Pohádkové městečko</h1><p>Každá vyřešená úloha probudí další kousek městečka. Vyber si, co chceš procvičit.</p></div><div class="city-total"><strong>'+total+'</strong><span>ze 100 prvků žije</span></div></div><div class="city-board">'+order.map(id=>district(id,progress,selected)).join('')+'<div class="city-river" aria-hidden="true"><i></i><i></i><i></i></div><div class="city-core" aria-hidden="true"><span></span></div></div>'+(total===100?'<div class="world-finale"><b>Pohádkové městečko celé ožilo.</b> Zvládl jsi všech sto příběhů.</div>':'')+'</section>'}
function mini(topicId,progress,taskOrder){const d=districts[topicId],count=topicCount(topicId,progress),reward=d.rewards[(taskOrder||1)-1];return '<section class="district-mini" style="--accent:'+d.accent+'"><div class="mini-art">'+district(topicId,progress,topicId)+'</div><div><span class="eyebrow">'+d.name+'</span><h3>'+count+'/10 prvků probuzeno</h3><p>'+(count===10?'Celá čtvrť žije.':'Za tuto úlohu čeká: '+reward+'.')+'</p></div></section>'}
function nextUndone(topicId,currentId,progress,tasks){const completed=ids(progress),same=tasks.filter(t=>t.topicId===topicId),at=Math.max(0,same.findIndex(t=>t.id===currentId));for(let step=1;step<=same.length;step++){const task=same[(at+step)%same.length];if(!completed.has(task.id))return task}return null}
window.grade2World={districts,order,topicCount,render,mini,nextUndone};
})();