'use strict';
(()=>{
 const districts={
 prirozena:{name:'Číselný přístav',short:'Přirozená čísla',accent:'#60a5fa',icon:'numberline',rewards:['První molo','Sklad čísel','Jeřáb','Maják','Nákladní loď','Přístavní světla','Cesta k molu','Přístavníci','Druhá loď','Přístav v pohybu']},
 delitelnost:{name:'Dělitelné depo',short:'Dělitelnost',accent:'#34d399',icon:'hub',rewards:['První bedna','Řada balíků','Třídicí stůl','Rampa','Regály','Depo světla','Kontrolní stanice','Vozík','Pracovníci','Depo v provozu']},
 desetinna:{name:'Přesná promenáda',short:'Desetinná čísla',accent:'#fb7185',icon:'gauge',rewards:['První lavička','Měřicí sloup','Hodiny','Stánek','Fontána','Lampy','Zábradlí','Chodci','Hudebník','Promenáda žije']},
 zlomky:{name:'Zlomková kuchyně',short:'Zlomky a části celku',accent:'#fb923c',icon:'pie',rewards:['První stůl','Prkénko','Mísa','Pec','Police','Kuchyňská světla','Servírovací pult','Kuchař','Hosté','Kuchyně v provozu']},
 uhly:{name:'Úhlové náměstí',short:'Úhly',accent:'#fbbf24',icon:'angle',rewards:['První paprsek','Druhý paprsek','Pravý roh','Přímý průchod','Rozcestník','Náměstní světla','Hodiny','Socha','Návštěvníci','Náměstí září']},
 trojuhelniky:{name:'Trojúhelníkový park',short:'Trojúhelníky',accent:'#f87171',icon:'triangle',rewards:['První vrchol','Druhý vrchol','Třetí vrchol','První cesta','Druhá cesta','Parková světla','Altán','Stromy','Návštěvníci','Park v plném květu']},
 soumernost:{name:'Zrcadlová zahrada',short:'Osová souměrnost',accent:'#22d3ee',icon:'mirror',rewards:['První zrcadlo','Osa zahrady','Dvojice stromů','Dvojice laviček','Jezírko','Lampy','Brána','Sochy','Návštěvníci','Zahrada v rovnováze']},
 obvodObsah:{name:'Stavitelské nádvoří',short:'Obvod a obsah',accent:'#4ade80',icon:'quad',rewards:['První zeď','Druhá zeď','Brána','Dlažba','Záhon','Nádvořní světla','Altán','Mistr stavby','Návštěvníci','Nádvoří hotové']},
 krychleKvadr:{name:'Krychlová továrna',short:'Krychle a kvádr',accent:'#c084fc',icon:'cube',rewards:['První blok','Druhá vrstva','Třetí vrstva','Dopravník','Sklad','Tovární světla','Jeřáb','Mistr výroby','Expedice','Továrna v chodu']},
 prevody:{name:'Centrální stanice',short:'Převody a vícekrokové úlohy',accent:'#f472b6',icon:'rail',rewards:['První kolej','Nástupiště','Cedule','Hodiny','Lavičky','Stanice světla','Přijíždějící vlak','Cestující','Výpravčí','Stanice v pohybu']}};
 const order=Object.keys(districts),ids=p=>new Set(Array.isArray(p)?p:[]);
 function topicCount(topicId,progress){const completed=ids(progress);let n=0;for(let i=1;i<=10;i++)if(completed.has(`g6-${topicId}-${String(i).padStart(2,'0')}`))n++;return n}
 function icon(type){const x={numberline:'<path d="M15 45h70"/><path d="M25 39v12M40 39v12M55 39v12M70 39v12"/>',hub:'<circle cx="50" cy="47" r="8"/><path d="M50 39V15M50 55v24M42 47H18M58 47h24"/>',gauge:'<path d="M20 65a30 30 0 0 1 60 0"/><path d="M50 65L68 40"/>',pie:'<circle cx="50" cy="47" r="28"/><path d="M50 47L50 19M50 47L74 61M50 47L26 61"/>',angle:'<path d="M22 70L50 28L82 70"/><path d="M40 58a16 16 0 0 1 20 0"/>',triangle:'<path d="M50 18L84 72H16z"/>',mirror:'<path d="M50 15v60" stroke-dasharray="4 5"/><path d="M45 70L30 30h10l5 40z"/><path d="M55 70L70 30h-10l-5 40z"/>',quad:'<path d="M20 65h40l20-40H40z"/>',cube:'<path d="M30 30l20-12 20 12v30L50 72 30 60z"/><path d="M30 30l20 12 20-12M50 42v30"/>',rail:'<path d="M15 65h70M15 55h70"/><path d="M22 55v10M37 55v10M52 55v10M67 55v10"/>'};return `<svg viewBox="0 0 100 90" aria-hidden="true">${x[type]}</svg>`}
 function district(topicId,progress,selected){const d=districts[topicId],count=topicCount(topicId,progress),done=count===10;return `<button class="city-district progress-${count} ${selected===topicId?'selected':''} ${done?'complete':''}" data-city-topic="${topicId}" style="--accent:${d.accent}" aria-label="${d.name}: ${count} z 10 dokončeno"><span class="district-sky"><i class="orb feature f10"></i><i class="cloud cloud-a feature f2"></i><i class="cloud cloud-b feature f7"></i></span><span class="district-land"><i class="building main feature f1"></i><i class="building side feature f3"></i><i class="bridge feature f4"></i><i class="nature n1 feature f5"></i><i class="nature n2 feature f6"></i><i class="light l1 feature f2"></i><i class="light l2 feature f8"></i><i class="person p1 feature f9"></i><i class="person p2 feature f9"></i><i class="motion feature f10"></i></span><span class="district-icon">${icon(d.icon)}</span><span class="district-copy"><b>${d.name}</b><small>${d.short}</small><em>${count}/10</em></span><span class="district-complete">ČTVRŤ OŽILA</span></button>`}
 function render(progress,selected='all'){const total=Array.from(ids(progress)).filter(id=>/^g6-/.test(id)).length;return `<section class="city-world ${total===100?'world-complete':''}" aria-label="Objevné město, herní svět 6. ročníku"><div class="city-heading"><div><span class="eyebrow">HERNÍ SVĚT 6. ROČNÍKU</span><h1>Objevné město</h1><p>Každá dokončená úloha probudí další část města. Vyber si čtvrť v libovolném pořadí.</p></div><div class="city-total"><strong>${total}</strong><span>ze 100 prvků žije</span></div></div><div class="city-board">${order.map(id=>district(id,progress,selected)).join('')}<div class="city-river" aria-hidden="true"><i></i><i></i><i></i></div><div class="city-core" aria-hidden="true"><span></span></div></div>${total===100?'<div class="world-finale"><b>Objevné město je dokončené.</b> Propojil jsi všech sto příběhů, modelů, postupů a kontrol reality.</div>':''}</section>`}
 function mini(topicId,progress,taskOrder){const d=districts[topicId],count=topicCount(topicId,progress),reward=d.rewards[(taskOrder||1)-1];return `<section class="district-mini" style="--accent:${d.accent}"><div class="mini-art">${district(topicId,progress,topicId)}</div><div><span class="eyebrow">${d.name}</span><h3>${count}/10 prvků probuzeno</h3><p>${count===10?'Celá čtvrť žije.':`Za tuto úlohu čeká: ${reward}.`}</p></div></section>`}
 function nextUndone(topicId,currentId,progress,tasks){const completed=ids(progress),same=tasks.filter(t=>t.topicId===topicId),at=Math.max(0,same.findIndex(t=>t.id===currentId));for(let step=1;step<=same.length;step++){const task=same[(at+step)%same.length];if(!completed.has(task.id))return task}return null}
 window.grade6World={districts,order,topicCount,render,mini,nextUndone};
})();